### ISSUE TITLE
[Question] Information screen scroll behaviour

### ISSUE THREAD

**Issue by Andihawke** [jurialmunkey/skin.arctic.horizon#115]
hey it's me again :-)
just a question about the scroll behaviour inside info screen.

if i longpress the down button on the remote, the infoscreen closes and returns to the previous screen. 

it just feels a bit unnatural because i don't know how far I have to scroll down.
maybe it's better just to return with the back button? what do you think about it?

another little issue:
if i longpress the up button on the remote, the infoscreen closes and returns to the previous screen and it ends in an infinite loop. (as long as i press the up button)

![DSC_0212](https://user-images.githubusercontent.com/17460997/78888466-f63f9580-7a61-11ea-8763-623ca375c2d4.JPG)

**Comment by jurialmunkey** [comment]
Yeah I think I agree. Main reason I had that behaviour originally was because I was worried about people who would accidentally trigger the plot overlay onup and then wouldn't know how to get out - but that was also from when the plot overlay didn't have critics consensus and so was usually only one page. With critics consensus it is nearly always at least two pages which creates the trickiness about knowing when to stop scrolling.

Should be fixed now.
