### ISSUE TITLE
[Issue] Recordings artwork changes

### ISSUE THREAD

**Issue by sammy2142** [jurialmunkey/skin.arctic.horizon#121]
After upgrading from v0.1.91 to v0.1.96 landscape art started to work and posters were now full size which was great:
![landscape recordins](https://user-images.githubusercontent.com/5837771/78998585-d59a3d00-7b40-11ea-81e2-7f0b3c866250.png)
![full_sizeposter](https://user-images.githubusercontent.com/5837771/78999301-3d04bc80-7b42-11ea-9911-77ae78306a97.png)
Unfortunately this only worked on existing recordings - any new recordings still used the old small poster (see "flushed away" at the end of the widget).
Also a small issue for existing recordings when upgrading to v0.196 - the posters are cropped/fit to width in this screen.
![zoomed in poster](https://user-images.githubusercontent.com/5837771/78998841-5d804700-7b41-11ea-9fd0-17ecc19acc0e.png)
 
Ps. did you remove the other view from recordings (we used to have two to choose from)?
Regards

**Comment by jurialmunkey** [comment]
Did you change backends? Or update PVR - The skin wouldn't change the artwork type - it would be differences in how the PVR is now setting the artwork.

Yep, can confirm that I've accidentally removed the other views. Adding them back in now.

The artwork cropping is going to be an ongoing issue that I'm trying to patch where I can. The code involved in selecting artwork was overly complex and I've been trying to simplify it to improve performance where I can. As a side-effect I'm expecting cases like this where I haven't tested (or can't because I don't have your particular setup) - Just let me know about any like this and I'll try to fix where I can.

**Comment by jurialmunkey** [comment]
@sammy2142 - Can you test v0.1.98? I think most of these issues should now be fixed.  I can't do anything about the artwork scaling thing (first two screenshots) because that looks like something has changed in your PVR where Art(fanart) and Art(poster) are now getting set (the shrunk ones are because the artwork was only set as Icon).

**Comment by sammy2142** [comment]
Hi - thanks I can confirm the issue in the third screenshot has been fixed:
![tv_screen](https://user-images.githubusercontent.com/5837771/79044860-abf41b00-7bff-11ea-89b0-ded8818c197a.png)

Thanks for the info - I've been testing nextpvr 5.0 (it's just moved from beta to stable).
I will try and investigate whats happening with the artwork and backend

**Comment by sammy2142** [comment]
After digging around some kodi and nextpvr log files it appears the fanart files are being requested and sent by nextpvr.  The only errors in the kodi logs were from recordings with no artwork (which returned an error code).
I have no idea whats happening to the fanart?

**Comment by sammy2142** [comment]
After some further testing all of the recording fanart images work in the default estuary screen. I'm not sure why they don't appear in arctic horizon widgets - any chance you could look into this @jurialmunkey thanks :)
![fanart-png](https://user-images.githubusercontent.com/5837771/79054405-60ac2d80-7c3c-11ea-8d9a-bc7fa59fc529.png)

**Comment by sammy2142** [comment]
Just to clarify the last post; fanart does appear in arctic horizon as the background on recordings. 
It's just missing from widgets when set to landscape aspect ratio.
Is fanart supposed to show here or just landscape - can it fallback to fanart if no landscape if that is the case?

![fanart](https://user-images.githubusercontent.com/5837771/79904839-3fea9180-840d-11ea-9737-349a2c46c013.png)

**Comment by jurialmunkey** [comment]
> Just to clarify the last post; fanart does appear in arctic horizon as the background on recordings.
> It's just missing from widgets when set to landscape aspect ratio.
> Is fanart supposed to show here or just landscape - can it fallback to fanart if no landscape if that is the case?

Ah okay, that's useful info. I'm fairly certain I know what the issue is now - it's just finding a way to fix it!

**Comment by jurialmunkey** [comment]
@sammy2142 - Can you test v0.2.12? I'm hoping that will fix the problem.

**Comment by sammy2142** [comment]
It's all fixed now and looks great (it also fixed the padding issues with posters) :)
![home](https://user-images.githubusercontent.com/5837771/79972919-93e98a80-848e-11ea-9987-831cdf30954d.png)
![poster](https://user-images.githubusercontent.com/5837771/79972969-a82d8780-848e-11ea-98d4-fc9872a71959.png)
