### ISSUE TITLE
Scores and clear art not being removed when moving between elements in a list

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/skin.arctic.horizon#138]
I noticed that scores from TMDB, Rotten Tomatoes, etc. and the clear art images take some time to load (or at least with my current connection). The problem with that is that, when changing from one entry to another, the scores from the previous entry remain until the new ones are fetched. Would it be possible to just remove those elements while waiting for the right ones for that entry?

**Comment by jurialmunkey** [comment]
This issue is more related to TMDbHelper.

I've just introduced a threaded approach in TMDbHelper for setting the different properties, so I think it should probably now better handle this type of issue where there is a delay in retrieving ratings/artwork.

Can you test latest version of TMDbHelper and see if it is functioning better for you.

**Comment by juanma-cvega** [comment]
I just tested it and it looks better now in terms of responsiveness. But, and this is a personal opinion, I think it makes a weird effect having scores appear independently of each other. When you change entries you see many icons appearing and disappearing really fast. I think the effect would be nicer it they all showed up and disappear  at the same time.

**Comment by jurialmunkey** [comment]
There's not much that can be done about that. All the ratings are retrieved at the same time and then the properties are set for each rating. Its not possible to set multiple properties simultaneously - they have to be set one after the other. Though, it is just about the simplest process possible, so if there is a noticeable delay then that's really a system performance issue.

In the past I tried setting an IsUpdating flag and waiting for that to resolve, but that just introduced other issues with flickering visibility on item changes. In terms of what works -- either the properties aren't cleared and are only updated (how it was before) - which looks good but has issues if there is a delay in retrieving the ratings because the info no longer matches the item; or the properties are cleared when the item changes and then set again after being retrieved (current method - which doesn't look as good but ensures that the info always matches the item).
