### ISSUE TITLE
Search overlay shows up again after adding a TV show to a trakt list

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/skin.arctic.horizon#152]
I actually don't know if this is skin, themoviedb helper addon or kodi related. The description describes the problem as only happening after adding to a trakt list but I think there are other ways to trigger it. So basically after searching for a TV show and adding it to a trakt list, the search overlay shows up again, forcing me to reenter the search string, otherwise it goes to another Kodi screen.

**Comment by jurialmunkey** [comment]
Not skin related.

It's an issue with needing to call `Container.Refresh` after syncing with Trakt to make sure the listitems get the updated info -- really more important for Trakt History because of watched marks but I refresh container after doing any Trakt list updates just in case there is something relevant to the current listing.

The problem is with search queries the path isn't updated with the search query, so when the container is refreshed the plugin gets called again and notices there isn't a search query so prompts the user to enter one.

I've added a workaround in latest TMDBHelper to force the path to update with the search query. The downside is that the search query will load and then is refreshed thereby causing the container to reload - but at least the first search is cached so the reload should be fast.

**Comment by drinfernoo** [comment]
@jurialmunkey Does this help with the "bug" where you search, and then that search stays in the search window even when you search again?

**Comment by jurialmunkey** [comment]
@drinfernoo - I'm not aware of that bug ??? What exactly happens? Are you talking about TMDbHelper search? Or are you talking about Arctic Horizon's customisable globalsearch replacement?

**Comment by drinfernoo** [comment]
You know what... I've prove myself wrong 😅

While trying to get this on video to show what I thought was the bug, I realized that if I wait long enough, it actually does show the new thing I searched. It's only a matter of the label carrying over from the previous search.

**Comment by jurialmunkey** [comment]
> 
> 
> You know what... I've prove myself wrong 😅
> 
> While trying to get this on video to show what I thought was the bug, I realized that if I wait long enough, it actually does show the new thing I searched. It's only a matter of the label carrying over from the previous search.

Ah, you mean in Arctic Horizon's search page -- Yeah, if you reopen a window and Kodi still has the window in memory then the containers will have all the old content. You can't do `<visible>!container.isupdating</visible>` because the container wont update if it isn't visible -  so to get around that, I use a conditional fade animation to hide them and show a busy spinner instead. Technically the old items are still in the container when it is updating (and hence the old label), you just can't see them because the opacity is set to 0.
