### ISSUE TITLE
[Request] Keep information row on widgets when there is more than one in display

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/skin.arctic.horizon#155]
Just wanted to ask, I know you don't want to add features to this skin just to keep everyone happy and leave it as simple as possible. Would it be possible to add an option to the skin to always keep the row that shows information about each entry on the widget the same way it does when there is only one widget? The same way it does in the screenshot below and also letting a little bit of the next widget be shown at the bottom so at least the title of the widget could be seen.

<img width="1440" alt="Screenshot 2020-05-05 at 19 29 38" src="https://user-images.githubusercontent.com/6765894/81096559-ddae8800-8f06-11ea-9900-50de8cad64d5.png">

**Comment by drinfernoo** [comment]
Just make pages with only one widget.

**Comment by juanma-cvega** [comment]
> Just make pages with only one widget.

That's an option but I think that defeats the purpose of using a multi widget skin if you only create one widget per item. It's just a suggestion, by no means I demand the feature to be done. Just wanting to ask about it as I saw a comment on reddit from someone asking the same question so wonder if @jurialmunkey would consider it something useful to the skin.

**Comment by jurialmunkey** [comment]
It's not really possible. I need to know the widget container ID to take the info from at the point that the widget group changes. It isn't possible to determine which widget is going to be "visible" because technically all widgets in the page are visible, just some are onscreen and some aren't. 

I have to guess the ID - so I reduce it to one possible widget to make sure my "guess" is always correct. I definitely know what the ID of the first widget will be because the widget IDs follow a strict numbering system: `3MMWW` where MM is menu position and WW is widget position - e.g. 30201 is 1st widget for 2nd menu.

If I made it so that the container ID was set onfocus, then you would have the wrong info or no info until you focused the widget which really defeats the purpose.

The other option is to have a separate info group control as part of each individual widget. That would require a separate skin variable for title, infoline, plot and clearart for every possible widget container ID. 50 menus x 100 widgets x 4 info types = 20,000 variables. Even if we made it so only the first 5 widgets could have info, that's still 1,000 variables that need to be written.

**Comment by drinfernoo** [comment]
I'm happy with the current implementation 🤷🏽‍♂️

**Comment by jurialmunkey** [comment]
> 
> 
> I'm happy with the current implementation 🤷🏽‍♂️

Yeah. It's one of those things where if there was a relatively uncomplicated way to achieve it, I would implement it in a heartbeat. It's just that the complexity required currently to achieve it heavily outweighs the benefit.

Variables that accept $PARAM[] are desperately needed in the skinning engine. It would simplify soooo many things that currently require hacky workarounds.

**Comment by juanma-cvega** [comment]
Ok, I didn't know it was that complicated to do. Sorry for asking, I've never done any Kodi skinning so I cannot know when something is simple or complicated, I can only request and test things out 😄 I had the experience of the Aura (I don't know if regular or mod) where you could see the description of the item selected, either with the Netflix style at the top or as a sliding box next to it so I thought it would be something similar to that.

**Comment by jurialmunkey** [comment]
> 
> 
> Ok, I didn't know it was that complicated to do. Sorry for asking, I've never done any Kodi skinning so I cannot know when something is simple or complicated, I can only request and test things out 😄 I had the experience of the Aura (I don't know if regular or mod) where you could see the description of the item selected, either with the Netflix style at the top or as a sliding box next to it so I thought it would be something similar to that.

Oh it's a completely reasonable request! I wouldn't expect anyone to know the underlying reasons - just explaining why it's not possible.

There are simpler ways to do it - but they all involve compromises that I don't want to make.

Oh and that would've been Aura mod. The original Aura never had anything like that in it.
