### ISSUE TITLE
[Question] Speed up widgets from TheMovieDB Helper with threads

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/skin.arctic.horizon#158]
I just wanted to ask and I guess you have done whatever Kodi allows you to do already. Are threads configured to speed up the loading of widgets? I love the way you can customise the menu adding different widgets to each entry. In my case I have Movies, TV shows, Anime, Kids, Live TV, Catch up, games and settings, each one with different widgets. But I realised they tend to load in the order they are presented on screen for each menu entry descending from the top one. I guess there are threads already been used because some widgets take longer than others (specially Trakt ones) and that doesn't stop the next widgets to eventually load up but I would like to know whether this could be configured based on system specs and if there is still room for performance improvements here. Or if this is totally unrelated to the skin and it's Kodi the one that handles the whole thing. Ever since the Leia version I've found that Kodi's interface tends to be rather slow at times so maybe this is something they need to improve on their side.

**Comment by jurialmunkey** [comment]
Unrelated to both the skin and the plugin. Kodi loads every plugin container (i.e. each widget) as a completely separate instance. As you correctly surmise, the loading by Kodi is definitely is threaded.

I'm not sure how many threads are involved - i.e. I'm not sure if every container gets loaded as an individual thread all at the same time or if there are X number of job threads which each sequential load containers from a queue. Judging from how widgets generally tend to load, I'm guessing it is the latter and maybe based on how many cores the CPU has.

There's not really any threading that can be done inside the plugin, as the logic typically has to follow a linear process (e.g. retrieve response from API, manipulate the data, create listitems)

In terms of TMDbHelper widgets, the biggest single loading cost is Fanart.TV as requests to that API definitely take the longest. Disabling fanart tv in the TMDbHelper settings can make a big difference to the loading times of the widgets. The in-progress / your next episodes widgets are also very slow because they involve a lot of lookups.

**Comment by juanma-cvega** [comment]
Ok, I'll disable Fanart.TV and see how it behaves. For the in progress widget, is this related to loading from the addon or it's the same thing when loading from local library? That's the one I use library integration with and the main reason I suggested the creation of playlists when importing. That way there is no need to make API requests. About the In progress widget, I noticed the widget takes quite a long time to load an empty list when there are no episodes left to watch. Is that also Kodi related?

**Comment by jurialmunkey** [comment]
> For the in progress widget, is this related to loading from the addon or it's the same thing when loading from local library?

The online lookups are always more expensive than local db lookups.

> That's the one I use library integration with and the main reason I suggested the creation of playlists when importing. That way there is no need to make API requests.

There's a big difference between the two though. 

Kodi in-progress widget is only based on library watched data - it displays each show that has at least one watched episode and one unwatched episode.

TMDbHelper in-progress uses your Trakt data - it displays any show where there are still episodes you haven't watched yet. The two big advantages are: (1) being online means you can watch on any device and keep track of your progress; and (2) it will display shows that you have started rewatching even if every episode was previously marked as watched. 

For me these advantages far out way the cost of slow loading.

> About the In progress widget, I noticed the widget takes quite a long time to load an empty list when there are no episodes left to watch. Is that also Kodi related?

Yep that's the slowest possible scenario. What it does is pull a list of all your watched tvshows sorted in order of recently watched. It then checks your Trakt account for each individual show to see if it is in-progress. If the show's in-progress it is added to the list. Once it finds 10 shows (or 20 depending on the settings), then it creates the list. 

So if you have an empty list because you finished everything that's going to take the longest because it literally has to check every single show. The results are cached until you watch another episode, so it should be much faster the second time around (at least until you watch something else).
