### ISSUE TITLE
[Bug] Weather Window Inconsistencies

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.horizon#170]
First of all, the "Install Weather Fanart" option doesn't appear to do anything... so I am unable to set fanart for the weather window.

Also, the icon on the menu isn't colored as in the rest of the skin 😉 

![image](https://user-images.githubusercontent.com/2319508/81616548-8857f800-9398-11ea-8e09-7665319331d0.png)

**Comment by drinfernoo** [comment]
You know what, I had somehow disabled "Weather Fanart - Multi", and enabling it caused them to show in the background. The option disappeared from the menu, and the fanart is now showing :+1:

**Comment by jurialmunkey** [comment]
Yeah I can't re-enable disabled addons from the skin -- only installing is possible from a skin -- the ability to re-enable addons is only available in Matrix. System.HasAddon only checks if an addon is enabled -- so to the skin a disabled addon looks the same as one that isn't installed. That's why it shows install weather fanart but doesn't do anything.

In terms of the icon -- yeah I think there are a few of those types of menus that I need to consolidate. I've got most of them but there's still a few left overs from AZ2.

**Comment by drinfernoo** [comment]
Is it possible to use other weather fanart?

**Comment by jurialmunkey** [comment]
> 
> 
> Is it possible to use other weather fanart?

Nope, because there's differences in the folder structure.

Some are structured:
`/resources/{weather-code}.jpg`

Others are structured
`/resources/{weather-code}/{index}.jpg`

I use the second approach in the skin and Weather Fanart Multi is the only pack  out of the four in the repo that uses that approach (because it has multiple images for each weather code). It's a pain to try to implement two different approaches for weather fanart, plus Multi is by far and away the best looking.

Prairie is ugly af.
Faded isn't really suited as background images - it's more for a backing panel type of thing.
Single is okay but pales in comparison to Multi which has better artwork and a more cohesive style overall.
