### ISSUE TITLE
[Bug] - Some cast artwork missing.

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#177]
A few years ago when I used Guilouz's skins, The information would instantly appear if I clicked on the info button. I just tried Estuary MOD and it's still very fast. Arctic Horizon can sometimes be a bit slow retrieving info. Do you think it's possible to improve the speed?

<a href="https://imgur.com/mrKUYJD"><img src="https://i.imgur.com/mrKUYJD.png" title="source: imgur.com" /></a>

Thanks

**Comment by jurialmunkey** [comment]
It's because in Estuary mod the info button just fakes the info dialog by showing the info available to videoosd but in a layout that mimics the info dialog -- you'll notice in Estuary mod that many parts of the normal info dialog are missing (e.g. the buttons).

Since I'm showing most of the info available to the videoosd on-screen already, I have the info button open TMDbHelper's extended info dialog instead. That way you get the real info dialog rather than a faked one.

**Comment by Blurayx** [comment]
Ok, Thanks!😀

**Comment by Blurayx** [comment]
when I use AH the cast is very limited with blank images
e.g
[img]https://i.imgur.com/iB741x2.png[/img]

[img]https://i.imgur.com/FOcbUM2.png[/img]

Estuary MOD
[img]https://i.imgur.com/DbIdKyK.png[/img]
[img]https://i.imgur.com/xoB0yR7.png[/img]
[img]https://i.imgur.com/cON3glh.png[/img]

**Comment by Blurayx** [comment]
Update
In this mode I can see the latest cast member(Lisseth Chavez)
[img]https://i.imgur.com/PN5HsTt.png[/img]
[img]https://i.imgur.com/VRgyN0N.png[/img]

**Comment by jurialmunkey** [comment]
@Blurayx - Can you test latest? Hopefully should fix the issue.

**Comment by Blurayx** [comment]
Perfect!!!! 
<a href="https://imgur.com/MfhYuwS"><img src="https://i.imgur.com/MfhYuwS.png" title="source: imgur.com" /></a>

Thank you 😀

**Comment by Blurayx** [comment]
> Update
> In this mode I can see the latest cast member(Lisseth Chavez)
> [![](https://camo.githubusercontent.com/d046972860da56a6f84329c22a897528ce58fb8e/68747470733a2f2f692e696d6775722e636f6d2f504e35487354742e706e67)](https://imgur.com/PN5HsTt)
> [![](https://camo.githubusercontent.com/ea1814243abeed1b44e22d27304360b1a29a9270/68747470733a2f2f692e696d6775722e636f6d2f565267794e304e2e706e67)](https://imgur.com/VRgyN0N)

one more question. why is the info instant in this mode?

**Comment by Blurayx** [comment]
> Update
> In this mode I can see the latest cast member(Lisseth Chavez)
> [![](https://camo.githubusercontent.com/d046972860da56a6f84329c22a897528ce58fb8e/68747470733a2f2f692e696d6775722e636f6d2f504e35487354742e706e67)](https://imgur.com/PN5HsTt)
> [![](https://camo.githubusercontent.com/ea1814243abeed1b44e22d27304360b1a29a9270/68747470733a2f2f692e696d6775722e636f6d2f565267794e304e2e706e67)](https://imgur.com/VRgyN0N)

one more question. why is the info instant in this mode?

**Comment by jurialmunkey** [comment]
It's instant because the focused item in the list container is what holds the info. The info dialog doesn't load any info itself, it just "arranges" the existing info for the focused item. Outside the list container, if you opened the info dialog it would be completely empty because there's no list and no focused item. That's why Estuary Mod "fakes" the info dialog by creating a custom dialog with info from the VideoPlayer.

In Arctic Horizon, I use the real info dialog by using a few tricks:

- TMDbHelper calls a custom window with a widget hidden offscreen.
- The widget contains a smart playlist with rules that can *only* match the playing item.
- Once the widget loads, TMDbHelper simulates the user pressing info on the widget.

For items not in the library, the smart playlist is replaced with a TMDbHelper widget. Previously I was only using the online TMDb widgets from the OSD, which is why some cast info was missing (probably not updated on TMDb website yet).
