### ISSUE TITLE
[Bug] Subtitle Placement in Trailer Window

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.horizon#178]
![image](https://user-images.githubusercontent.com/2319508/82629850-cc6fa780-9ba5-11ea-9b68-873b8facc46b.png)
That's pretty much it 😅

**Comment by jurialmunkey** [comment]
Can't control where the subtitles are placed at all unfortunately.

**Comment by drinfernoo** [comment]
Bummer, alright 😩

**Comment by jurialmunkey** [comment]
I've never experienced that before though -- I didn't even realise that subtitles showed at all with a videowindow control. I thought they only showed in fullscreen but it appears not!

It's actually a real pain that can't control subtitle positioning because it would be really useful to be able to shift them up when the osd controls are visible in fullscreen video.

**Comment by drinfernoo** [comment]
It occured to me that... these are there

￼

 But I assume those take effect on all windows a well. Can you even affect these?

**Comment by jurialmunkey** [comment]
> But I assume those take effect on all windows as well. Can you even affect these?

Technically no. I think it's possible to hack it using JSONRPC but that's an ugly approach -- plus not really a good idea to mess around with people's screen calibration settings
