### ISSUE TITLE
[Bug] Updating 

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#180]
When updating AH my library view defaults to Tag View. I noticed this yesterday and when I just updated to 0.2.72
<a href="https://imgur.com/4mS5YLp"><img src="https://i.imgur.com/4mS5YLp.png" title="source: imgur.com" /></a>

<a href="https://imgur.com/UCIDPzs"><img src="https://i.imgur.com/UCIDPzs.png" title="source: imgur.com" /></a>

**Comment by jurialmunkey** [comment]
Really odd.
How did you update and what view did you have set before?

Also can you get these files for me (just upload to something like pastebin is fine)
`skin.arctic.horizon/1080i/script-skinviewtypes-includes.xml`
and
`kodi/userdata/addon_data/script.skinvariables/skin.arctic.horizon-viewtypes.json`

**Comment by Blurayx** [comment]
Do you want me to upload skin.arctic.horizon/1080i/script-skinviewtypes-includes.xml  before the tag view or with the tag view?

**Comment by Blurayx** [comment]
1. Install from zip file
2. landscape
Dropbox AH folder
https://www.dropbox.com/sh/p7ma5rl8ws9vg18/AAA0ZpdQ_mpaXuIgkH6eP00ca?dl=0

**Comment by jurialmunkey** [comment]
Thanks - you've uploaded the "script-skin*variables*-includes.xml" file though -- I need the "script-skin*viewtypes*-includes.xml" file from the skin folder.

**Comment by jurialmunkey** [comment]
Actually... I'm guessing you're missing that file! And I think I just realised why.

**Comment by jurialmunkey** [comment]
Okay I think it should be fixed now. Need newest version of script.skinvariables

**Comment by Blurayx** [comment]
This is so wired.  "script-skinvariables-includes.xml" appeared when I changed the view type back to landscape
<a href="https://imgur.com/HZSly6c"><img src="https://i.imgur.com/HZSly6c.jpg" title="source: imgur.com" /></a>
<a href="https://imgur.com/PTftjQt"><img src="https://i.imgur.com/PTftjQt.jpg" title="source: imgur.com" /></a>

**Comment by Blurayx** [comment]
Working now 😀
Did you get the same bug on your setup?

**Comment by jurialmunkey** [comment]
> 
> 
> Working now 😀
> Did you get the same bug on your setup?

I didn't notice it since I was messing around with things. It was only when you attached the wrong file that the penny dropped...

Basically, entering the home screen triggers the script to build the file. To avoid constantly rebuilding, the script stores a hash and only rebuilds if there are view changes. Problem was, I forgot that updates will overwrite the skin folders, thus deleting the file - but the script thinks it doesn't need to rebuild it since it stored a hash.

Solution was simple -- actually check that the file exists and if it doesn't rebuild it! 🤣

**Comment by Blurayx** [comment]
Glad it wasn't too hard to fix  😀

I love this skin. Definitely your best work to date!!!
