### ISSUE TITLE
TMDBHelper being too helpful for add-ons?

### ISSUE THREAD

**Issue by piejanssens** [jurialmunkey/skin.arctic.horizon#183]
Add-on RedBull TV: https://forum.kodi.tv/showthread.php?tid=340657&pid=2859094#pid2859094

Issue 1: After opening the add-on it shows 'Speelfilms' in the upper left (meaning 'Movies'). Preferrably this should display the title of the add-on.

![Schermafbeelding 2020-05-26 om 12 35 48](https://user-images.githubusercontent.com/829098/82895785-0e596e80-9f55-11ea-9501-2f219140bc1f.png)

Issue 2: In poster view the plot of the first movie that corresponds with the listitem title is being shown. In this example the list item title is 'Discover' and the plot is shown for "Discover Spot", which is the first result from TMDB. https://www.themoviedb.org/search?language=nl-NL&query=discover In addition I think it's the skin that is adding the day/date to this view, which has no use here.

![Schermafbeelding 2020-05-26 om 13 31 27](https://user-images.githubusercontent.com/829098/82895887-45c81b00-9f55-11ea-9883-2de82c9ec5f1.png)

Side question: is it possible to choose (and remember) a certain view type on one level (first level showing posters) another on a deeper level (showing list view)?

**Comment by piejanssens** [comment]
Seems to be add-on related.

**Comment by jurialmunkey** [comment]
> Issue 1: After opening the add-on it shows 'Speelfilms' in the upper left (meaning 'Movies'). Preferrably this should display the title of the add-on.

The upper left shows the section type. It's because the addon is incorrectly setting the content type of that section to Movies.

> Issue 2: In poster view the plot of the first movie that corresponds with the listitem title is being shown. In this example the list item title is 'Discover' and the plot is shown for "Discover Spot"

See above. Addon is incorrectly setting the content type to Movies, so TMDbHelper is looking for a movie called "Discover" and is taking the first match.

The content type in this section shouldn't be set to anything as there is no content. These items are definitely not "Movies".

It's impossible for skins to display things correctly if addons don't set the correct content and dbtypes.

> In addition I think it's the skin that is adding the day/date to this view, which has no use here.

What would you display instead? The date and number of items is the fallback when there is no other relevant info to display. There needs to be some fallback label. People seem to dislike showing "No information available" so I show the date.

> Side question: is it possible to choose (and remember) a certain view type on one level (first level showing posters) another on a deeper level (showing list view)?

Viewtypes in Arctic Horizon are attached to content types. The addon should set appropriate content types which reflect the content being displayed. Available content types include videos, movies, tvshows, seasons, episodes, sets, albums, artists, songs, images, musicvideos, addons, games, genres, years, countries, directors, actors, studios, files and none.

**Comment by piejanssens** [comment]
> What would you display instead? The date and number of items is the fallback when there is no other relevant info to display. There needs to be some fallback label. People seem to dislike showing "No information available" so I show the date.
> 
> >

I would display nothing, an empty string.

**Comment by piejanssens** [comment]
What is the source property of a listitem for the sub title where it says "Geen informatie beschikbaar" on my screenshot?
