### ISSUE TITLE
Local media slow to start from movie information page 

### ISSUE THREAD

**Issue by Tee77** [jurialmunkey/skin.arctic.horizon#186]
Hi. I’ve noticed that movies in my local library take a while to start playing from the movie information page (the page that displays actors etc), but play instantly if I pull up the context menu on a movie in library view and select play. FYI my local content is on an external hard drive attached to a vero 4K. Thanks.

**Comment by jurialmunkey** [comment]
It's because TMDbHelper script needs to run first to deal with the window management of the info dialog. It's not the script itself that is slow - it's just sometimes Kodi takes a moment to run the script. Not much I can do about the delay without breaking the ability to navigate TMDbHelper via the info dialog.

I've added a busy indicator in the latest version of the skin so at least there is some visual feedback that you've actually clicked the button and something is happening -- before it could look like nothing was happening if Kodi was a bit delayed in starting the script.
