### ISSUE TITLE
Is there any plan to make this skin compatible with Kodi 19?

### ISSUE THREAD

**Issue by fernandoalonzo** [jurialmunkey/skin.arctic.horizon#192]
It would be nice to get this skin working in Matrix and tvOS. Great work, thank you!

**Comment by drinfernoo** [comment]
You need to install the GitHub version of the `matrix` branches of *at least* TMDbHelper and Skin Variables, and then this will install in Matrix.

**Comment by jurialmunkey** [comment]
It should mostly work as long as you install the dependencies. There were (and potential still are) issues with Android on Matrix and a missing PIL dependency that TMDbHelper requires - so I'm waiting for a fix for that, but the other platforms should work fine.

I won't make an "official" switch to Matrix until there's a Release Candidate of Kodi 19, since I don't like working on two different skin versions at the same time. But it definitely will get an official Matrix version eventually.
