### ISSUE TITLE
Ability to turn off the 'infinite wall'

### ISSUE THREAD

**Issue by GOvEy1nw** [jurialmunkey/skin.arctic.horizon#194]
It would be great if we could turn off the 'infinite scrolling' on a wall view so that you know when you've scrolled too far and can't scroll further etc. Just for this to be an optional on/off feature would be great.

![image](https://user-images.githubusercontent.com/45126527/84021202-10232900-a97c-11ea-9a44-8fb06186598b.png)

**Comment by jurialmunkey** [comment]
How would that work with multi directional scrolling? Think about it for a moment...

**Comment by jurialmunkey** [comment]
So the wall layout is like the following (00 is focused item)

```
 [-8] | [-7] [-6] [-5] [-4] [-3] [-2] [-1] | [00]
--------------------------------------------------
 [-1] | [00] [01] [02] [03] [04] [05] [06] | [07]
 [06] | [07] [08] [09] [10] [11] [12] [13] | [14]
--------------------------------------------------
 [13] | [14] [15] [16] [17] [18] [19] [20] | [21]
```


Now imagine we have 11 items in the wall. If it doesn't wrap it looks like this:
```
      |                                    | [00]
--------------------------------------------------
      | [00] [01] [02] [03] [04] [05] [06] | [07]
 [06] | [07] [08] [09] [10]                |
 --------------------------------------------------
      |                                    |
```

What happens when the user scrolls left or up from that situation?

Then imagine the focus is on the 11th item. It will look like the below:
```
 [02] | [03] [04] [05] [06] [07] [08] [09] | [10]
--------------------------------------------------
 [09] | [10]                               |
      |                                    |
 --------------------------------------------------
      |                                    |
```

What happens when the user scrolls right or down from there?

Or is the user just not allowed to scroll into the empty space?

**Comment by GOvEy1nw** [comment]
Hey, Generally I mean to have the option to switch it to something like the way Netflix, Disney+, Plex etc do it when inside a section, where they only have a certain amount of columns and the amount of rows is dependent on how many items you have within that section. Once you get the end of the column, you simply can't move beyond that point, once you get to the last row, you can't move further beyond that point either.

This would also mean people could press up to get back up to the button options within a hub as well as being able to press back to get back up there.

The key thing is, for example, I help setup my Dad's kodi, and we love the ease of use of this skin, but this part can become quite confusing as it looks like there's an infinite amount of movies in a section, and you're never sure when you've looked through them all or not.

Hope that makes sense.

**Comment by jurialmunkey** [comment]
I understand what you're asking for, as it was what I originally wanted to do - but there really is no sane way to do it.

The wall only works because fixed position select box means that I'm able to draw the posters on based upon their relative position. That means we are only loading a maximum of 52 items at any one time - the 30 items we see on screen, plus an extra 22 items offscreen so that movement looks smooth when we scroll.

A wall with a fixed number of columns would require getting posters according to their absolute position instead. There's a lot of technical reasons why that's not really feasible in the skinning engine - namely, since the skinning engine doesn't allow math operations, the only way to make such a wall is either: (1) load every single item in the list at once; or (2) use Kodi's built-in panel control that skins normally use when they have a wall view.

Option 1 is out of the question for obvious reasons. Load 500 library items all at once and you're going to have a bad time...

Option 2 also has problems because the panel wall control would be independent from the horizontal list control, meaning that movement in one won't be synchronized with the other. It defeats the purpose of the wall if you lose your place when you return back to the list.

Even if we didn't have these technically limitations and it were possible, the transition animation would be a nightmare. There are already 7 different transition animations in the current wall - one for each potential starting position in the list. Imagine if there are also 14 potential end positions in the wall since the position will no longer be fixed -- 7x14 = 98 different animations!!!

**Comment by jurialmunkey** [comment]
It's possible to do with a fixed focus position but it looks a bit weird when you reach the end because it is so empty.

![Honeyview_screenshot010](https://user-images.githubusercontent.com/4618719/84032242-6030d880-a9da-11ea-9d91-ea635cf818f8.jpg)


Less strange at the start of the wall...
![Honeyview_screenshot007](https://user-images.githubusercontent.com/4618719/84032285-70e14e80-a9da-11ea-8eff-d6cb95b341c6.jpg)

![Honeyview_screenshot011](https://user-images.githubusercontent.com/4618719/84032308-78a0f300-a9da-11ea-8476-2dca1e32c780.jpg)

**Comment by GOvEy1nw** [comment]
That's fair enough. After using it for a bit longer the wall makes much more sense for them now, so that's all good. Thanks for your help.

**Comment by tadly** [comment]
Chiming in from my own issue about the same topic (Retard me didn't search for existing issues, I'm sorry)

@jurialmunkey as you mentioned in the other issue you have a working proof of concept which is very nice to hear.
Reading through this issue the main limiting factor seems to be *smooth transition from single line to wall*.

While I'm sure it would look great if you manage to get that sorted, how about a additional simple wall view as we know it from other skins (including Zephyr 2)?

**Comment by jurialmunkey** [comment]
It doesn't fit in the design specs of the skin.

Have a look at this image detailing some of the basic design specs.

![Honeyview_screenshot024 (2)](https://user-images.githubusercontent.com/4618719/87153631-20bc1b80-c2fb-11ea-9c45-af9ab0b06699.jpg)

The two red posters indicate what a basic wall would look like following the standard specs of 80px padding from sides of window, 40px gap between items, and 320px item height.

As you can see, it is too tall to fit in the standard panel layout used for banners/icons/list. The top of the panel would add an extra 80px which would cut through the Title text. Remove the Title text and there is an additional 40px gap from the top line of the view (all views should fill that space, not fall short).

If I start disregarding the design specs, then the skin starts to look sloppy.


You can see how it would fit if I got rid of the Content/Sort line and the backing panel -- and that's actually because the base layout dimensions are from a much earlier iteration that didn't have those elements. When I introduced the panel element, I wasn't really thinking that I'd have any vertical views (the idea was all horizontal hence the "Horizon") - but now it's there, I can't really turn back without redesigning everything else...

**Comment by tadly** [comment]
Thanks for the detailed explanation. I *think* I understand what you mean.

When I said "simple wall view" I meant basically the "inifitiy wall" (so no additional information, just the posters) **without** the infinity aspect (scrolling only vertically or horizontally to stick with the "Horizon" name as you explained).

I guess I ignored the fact that this is very much a personal preference (only posters, no information) as **I** prefer seeing as much of my library as possible at once and if I want to know more about a item, I simply press `i`.

But you have done such a fantastic job on this already I'm sure something amazing will come from all of this :)
Looking forward to your proof-of-conecpt implementation.

For now, Zephyr2 it is (:
