### ISSUE TITLE
[Bug]Focus shifting to Play button before launching artist info page

### ISSUE THREAD

**Issue by onlytanmoy** [jurialmunkey/skin.arctic.horizon#203]
Minor issue but still...below are the steps to replicate

1. so say you are in info view of a movie
2. you see the play, trailer etc buttons on top
3. just under that panel, you have cast info with small posters of cast
4. you select one of the actors
5. press OK in remote to see info on him/her
6. the focus shifts to Play button immediately even though it will launch the artist info but still the focus shifts to play

Me as user got the impression it did not work out, so came down to artist poster and clicked again, same thing happened
eventually artist info page opened but focus should not shift - bit misleading :)

**Comment by jurialmunkey** [comment]
If the focus doesn't shift back to the default position then you get stuck when the next dialog opens because the control focus was previously on might no longer exist. For instance, the person info dialog is not going to have a cast list, so if the focus stays on the cast list then you're going to get stuck in no-mans land. Also, you want the next dialog to open on the default control -- if I don't return focus to the top, then the next dialog is going to open half way down amongst the lists.

The script that is run to open the window will display a busy indicator. The problem is that sometimes Kodi is a bit delayed in running the script, so you don't get immediate feedback that something is happening. There's nothing I can do about this from the skin side of things.

Also, you have the same problem if focus stays in the same position - people click multiple times because it seems like nothing happened. At least if focus gets sent back to the top you know that something is happening.

**Comment by onlytanmoy** [comment]
Got it, thanks for the detailed explanation.
Thank you for giving us all those beautiful skins.
