### ISSUE TITLE
[Feature] Left press submenu

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#21]
when I add a  Submenu eg TV Show, I can not see it on the home screen.

<a href="https://imgur.com/nuT1lQe"><img src="https://i.imgur.com/nuT1lQe.png" title="source: imgur.com" /></a>

**Comment by jurialmunkey** [comment]
Did you add the submenu widget?

**Comment by webmaher** [comment]
Widgets > Default Widgets > Other > Submenu

this is work..but i think most people like submenu hidden...so when you go to main menu and then push left arrow submenu open...

**Comment by Blurayx** [comment]
Sorry to confuse you. I like the submenu hidden. when I left arrow nothing happends

**Comment by jurialmunkey** [comment]
There is no hidden submenu in this skin. Options are either submenu widget or submenu hub.

**Comment by Blurayx** [comment]
Ok, Thanks

**Comment by jurialmunkey** [comment]
BTW, a left press submenu might make a return - I just haven't come up with something that I like yet.

I did try an expanding list but I couldn't get the transition nice. I have another idea though.

**Comment by Blurayx** [comment]
To be honest, I don't miss submenu, I really like the simplicity of this skin.

**Comment by jurialmunkey** [comment]
> 
> 
> To be honest, I don't miss submenu, I really like the simplicity of this skin.

Yeah I found the standard approach of expanding out the side menu to be a bit disorientating and I couldn't find a transition to it that wasn't confusing to new users as to what was going on.

I found with other people using the skin in my house that it was really easy for them to double press left and have the submenu open. Then they would be confused because they couldn't see the main menu items any more.

I do have an idea though, which I will definitely try out as I think it might help mitigate that sense of disorientation.

**Comment by jurialmunkey** [comment]
This issue is now resolved by the addition of popup submenus which can be added as a mainmenu shortcut action (popup menu on click)
`Customise Home > Action > Common > Submenu PopUp`

Added v0.1.57
---
Relevant Commit: https://github.com/jurialmunkey/skin.arctic.horizon/commit/d3fd5425c57da6a02476c8bf0b17c5d4ed4f0ce3

**Comment by Blurayx** [comment]
Thanks
