### ISSUE TITLE
[Bug] Unaired Episodes Only Red in Combined View

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.horizon#239]
To start, I'm not sure if this would be an issue for TMDbHelper (since I'm browsing in the add-on) or AH, but I noticed that unaired episodes only show the red italics in the combined season/episode view, and not when browsing the season.

**Comment by jurialmunkey** [comment]
Nothing to do with the skin. Label formatting is done in the plugin by adding `[COLOR=red][I]{label}[/I][/COLOR]` to the label field. 

The problem is that when container content is episodes in a MyNav window, Kodi is hard-coded to replace the label field according to the applied sort method. It doesn't happen for widget containers (hence not for the episodes in season view) because in a widget only listitems have a dbtype, not the entire container. 

For most sort methods, Kodi just swaps ListItem.Label with ListItem.Title - but I can't also format ListItem.Title because then skins have no way to get the clean title (which might be needed to pass to a plugin path or to a script).

Also when `sortby="episodes"` Kodi fills the label like so:
```
$INFO[ListItem.Season,,x]$INFO[ListItem.Episode,,. ]$INFO[ListItem.Title]
```
So you'd end up with "1x01. _Episode Title_" where only the italic part is red.


The only way around it is to remove sort methods in the plugin - no sort method means no label replacing. It's a bit of a Catch-22.  Thinking about it now, it might make sense to remove sort methods for episodes depending on whether the "Show unaired" option is enabled - at least that way the user gets to decide on which way to go with the trade-off.

**Comment by jurialmunkey** [comment]
^^^ That commit will "fix" the issue by removing sort methods for episodes if not hiding unaired.

**Comment by drinfernoo** [comment]
That seems like it shouldn't cause any issues... how many people sort episodes by anything besides episode order? 😅

Also, TIL commits can close issues in *other* repositories! 😁

**Comment by jurialmunkey** [comment]
> That seems like it shouldn't cause any issues... how many people sort episodes by anything besides episode order? 😅

Occasionally I find it useful to sort episodes by play count or last played to find something to watch that I haven't seen in a while - and there are a handful of shows where release order is different from production order (e.g. Freaks and Geeks). I guess it is maybe also useful to switch up things like "Your Next Aired" from recently watched order to release order.

Really though, those scenarios are not very common and I very much doubt that the average user even ever touches the sort method at all.

>Also, TIL commits can close issues in other repositories! 😁

Yeah I found out a couple of months ago that it was possible to do cross repo references, which is amazing! Wasn't sure if I could actually _close_ an issue that way though!
