### ISSUE TITLE
[Question] Viewtype

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#263]
I have a manually configured 30min workout menu. I don't know when it changed but now I only have one "viewtype" option

![1](https://user-images.githubusercontent.com/2873112/91633482-6c787080-e9e0-11ea-884f-e6497a12e142.jpg)
![2](https://user-images.githubusercontent.com/2873112/91633492-75694200-e9e0-11ea-8c08-39bb2cf64e8a.jpg)

**Comment by jurialmunkey** [comment]
"Files" container content has always had only one viewtype.

If you had other viewtypes before, then either you've started opening the node in files mode instead (i.e. direct link to the physical directory rather than a link to the source node) OR you've removed the content type from the source.

If this is from an addon then something in the addon has changed to give a different content type.

**Comment by Blurayx** [comment]
I reconfigured it again, I now have multiple view options. I don't know what happened because I never changed touched the menu.

![1](https://user-images.githubusercontent.com/2873112/91636941-7a3bef00-e9fc-11ea-8d4a-e4e1d77efc07.jpg)
