### ISSUE TITLE
[Bug] Weather

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#267]
Currently, it's Tuesday in the UK but the weather widget is displaying Today & Tuesday. I also tried the Met office widget.
![screenshot002](https://user-images.githubusercontent.com/2873112/91777205-22ada700-ebe7-11ea-9e3a-8fb61c12a274.png)

**Comment by jurialmunkey** [comment]
Working fine for me. Not a skin issue - all the labels are filled by the weather addon (in the skin it's just "Day.0.Name" "Day.1.Name" "Day.2.Name" etc.). I imagine the weather info for those services probably switches over to the next day some time early in the morning rather than right on midnight.

**Comment by Blurayx** [comment]
it's ok now but it was showing Today & Tuesday @ 23:30 before I decided to report it.

Thanks
