### ISSUE TITLE
[Bug] Widgets in Menu Vertical Orientation

### ISSUE THREAD

**Issue by taoxtrece** [jurialmunkey/skin.arctic.horizon#268]
Hi, in the vertical menu orientation at the end of widgets don't return to the initial position, i didn't find this issue in the horizontal menu orientation

**Comment by drinfernoo** [comment]
https://forum.kodi.tv/showthread.php?tid=351756&pid=2972933#pid2972933

**Comment by jurialmunkey** [comment]
In addition to the above - it makes no sense for widgets in vertical menu to wrap on the right side if it can't wrap going left. Otherwise if you overshoot whilst pressing right you wrap back around to the start and are forced to scroll the entire widget to get back to where you are.

Basically horizontal menu places emphasis on the ability of widgets to wrap when moving left/right and the vertical menu places emphasis on the ability to change widget pages when scrolling up/down through widgets.

**Comment by taoxtrece** [comment]
> In addition to the above - it makes no sense for widgets in vertical menu to wrap on the right side if it can't wrap going left. Otherwise if you overshoot whilst pressing right you wrap back around to the start and are forced to scroll the entire widget to get back to where you are.
> 
> Basically horizontal menu places emphasis on the ability of widgets to wrap when moving left/right and the vertical menu places emphasis on the ability to change widget pages when scrolling up/down through widgets.

ok im will using the new horizontal view, thanks but what happen with Submenu Hub? doesn't move is fixed
