### ISSUE TITLE
[Feature] - Display background/clearart from first widget when main menu is highlighted 

### ISSUE THREAD

**Issue by ricksrod** [jurialmunkey/skin.arctic.horizon#275]
I'm not sure if this is possible but thought I would check. 

When I land on my main menu item for TV Shows, it shows the default background image, and my first info widget is populated with data from the first item in that widget:

![Screenshot 2020-09-04 at 09 09 46](https://user-images.githubusercontent.com/62319780/92182778-d2a53d80-ee8f-11ea-8b76-8d9128fbebd3.png)

My request is to have the background and clearlogo populate from the item in the first info widget, whilst still on the main menu item. So the background and clearlogo would look like it does when the actual widget item is highlighted (below) but when the focus is still on the top level main menu:

![Screenshot 2020-09-04 at 09 16 23](https://user-images.githubusercontent.com/62319780/92182860-0a13ea00-ee90-11ea-8153-255be2814508.png)

Is that possible? Thanks

**Comment by jurialmunkey** [comment]
Unfortunately not possible for ratings and clearart (or at least I've not figured out a way to do it yet). The issue is that I need to tell TMDbHelper which widget ID to get info for -- that's fine if we're still on the same page (I just keep the same ID set), but if we change menu items then a different widget is going to be in view and we'll have the wrong ratings/clearart. The issue is that I need to set the ID when the user presses a direction but I don't know which widget will be in view until after the movement which is too late.

Background might be possible using the same trick as the infoline/plot uses to get info.

**Comment by ricksrod** [comment]
Thanks for the response, I understand the limitation!

The background is actually the main reason for this request, I think it would look a lot cleaner when switching between movies > tv shows if the background matched the data in the infowidget. 

I actually quite like the ratings/clearart only appearing when the widget is selected as it adds a nice 'pop' to the interface.

**Comment by drinfernoo** [comment]
@ricksrod
> I think it would look a lot cleaner when switching between movies > tv shows if the background matched the data in the infowidget.

Agreed, rather than the skin background.

**Comment by jurialmunkey** [comment]
^^^ That should fix the background issue.

Should also keep clearart visible for horizontal home (obviously hides when vert menu is focused). Clearart will only work if the actual item has clearart though -- i.e. if you rely on TMDbHelper to grab clearart, then that will only show if the widget is focused (same as additional ratings).

**Comment by ricksrod** [comment]
Looks amazing! Thanks


![Screenshot 2020-09-04 at 12 05 38](https://user-images.githubusercontent.com/62319780/92191448-2bcc9b80-eea7-11ea-9ddf-65ef13ab7323.png)
![Screenshot 2020-09-04 at 12 05 50](https://user-images.githubusercontent.com/62319780/92191457-2f602280-eea7-11ea-9318-948198952469.png)
