### ISSUE TITLE
[Bug] overlapping widgets

### ISSUE THREAD

**Issue by GOvEy1nw** [jurialmunkey/skin.arctic.horizon#276]
I looked back to see if anyone has mentioned this yet but I couldn't find anyone that had.

A few updates ago my 'settings' and 'submenu' widgets started overlapping like so: 
![20200904_224757](https://user-images.githubusercontent.com/45126527/92287254-2a2fc180-ef01-11ea-9b5b-0554bc47227e.jpg)

I've been updating the skin at every new update since then thinking it'd be fixed but to no avail.

Seems to only happen with these two widgets. I've tried removing them and re-adding them to try to fix it but that didn't work. The 'settings' widget is already set to be the top widget, but it's as though the submenu widget isn't taking into account the space needed for the settings widget.

**Comment by drinfernoo** [comment]
The Settings widget has only ever been designed to work as the only widget in a section, same as Weather.

**Comment by jurialmunkey** [comment]
The description of the widget literally states that it must be the only widget in the group. I'm not sure how much clearer I can make that...

![Honeyview_screenshot220](https://user-images.githubusercontent.com/4618719/92295273-bc22e300-ef70-11ea-9e80-93a24354fc80.jpg)

**Comment by GOvEy1nw** [comment]
Woah now, no need to be so short with me here. I'm a long time user of Arctic Horizon & as far as I can recall, these widgets never used to have these descriptions next to them, not when I originally set it up anyway. Also, the reason I'm reporting this is because it DID used to work fine, now it doesn't. So something has changed somewhere along the line.

**Comment by jurialmunkey** [comment]
> 
> 
> Woah now, no need to be so short with me here. I'm a long time user of Arctic Horizon & as far as I can recall, these widgets never used to have these descriptions next to them, not when I originally set it up anyway. Also, the reason I'm reporting this is because it DID used to work fine, now it doesn't. So something has changed somewhere along the line.

Wasn't intending to be rude - sorry if my comment came across that way. It's just that one of the first things I'd expect someone to do if they had issues with widgets after major changes to the home screen would be to try to reconfigure and/or readd them -- at which point it should become pretty clear from the section in the screenshot that such a configuration isn't supported.

That configuration may have worked in the past but it was never really designed to work that way (it never worked like that in AZ2 where the widget was originally from) and was only ever intended to be a fullscreen widget. The recent breaking changes were necessary to fix several long-standing navigation bugs that the settings widget had (e.g. this bug https://github.com/jurialmunkey/skin.arctic.horizon/issues/118). The changes were also necessary so that the horizontal menu would work properly.

**Comment by GOvEy1nw** [comment]
That's fair, thanks for the explanation! I can just switch to using the submenu as a regular submenu now I guess so that'll work fine. Also, as a side note, thanks for the updated 'wall' which now has the ability to be 'finite' as per a previous request #194 it works great & is less 'confusing' (though it wasn't really confusing personally) for my father etc to use.
