### ISSUE TITLE
[Bug] Returning to widget from library TV Show Seasons (TmdbHelper)

### ISSUE THREAD

**Issue by DaisyF8** [jurialmunkey/skin.arctic.horizon#28]
Click on a TV Show in a "Library-TvShows-by Title"-widget. Click browse. You see Seasons.

Click back.

You are in Tvshows overview by title. Clicking back again gives your Genres, Actors, Titles...

**Comment by jurialmunkey** [comment]
I can't replicate this issue. I open info on the show, press browse, go to seasons view, press back and I return to home screen.

Are you sure that something like skin shortcuts didn't reload the skin whilst you were navigating -- Kodi "forgets" path return history if you reload the skin.

Also are you pressing back on a remote? What is your remote back action mapped to?

**Comment by DaisyF8** [comment]
Behaviour also changed with me upgrading to 0.1.17.  As you say, pressing back (remote keyboard, back is backspace) in Seasons view takes me also back to home screen. 

Worth noting is that I thought you rewrote TmdbHelper to have you go back to the Information Screen. Now it just drops out to Home Screen.

Sorry I made a mess of this... 

I would say Solved.

**Comment by jurialmunkey** [comment]
> 
> Worth noting is that I thought you rewrote TmdbHelper to have you go back to the Information Screen. Now it just drops out to Home Screen.

This is not handled by TMDbHelper. It is just a standard kodi info dialog and TMDbHelper is not active. 

Either way, even if it were from a TMDbHelper info dialog it wouldn't be possible because once you browse to the seasons view you would no longer be inside the TMDbHelper window manager and are just in the normal kodi library.

Pressing back to reopen the info dialog only works when leaving the back press is *leaving* the TMDbHelper info dialog (because TMDBHelper is active at that stage and call a command on exit).
