### ISSUE TITLE
Actor window issue

### ISSUE THREAD

**Issue by daking1512** [jurialmunkey/skin.arctic.horizon#292]
would it be possible to have a sort of fade either around or only on the right side of the actor's picture?
 so that when the movie/tv show titles slide behind it they slide smoothly instead of having it look like a graphical bug

![Screenshot 2020-09-27 105638](https://user-images.githubusercontent.com/51313567/94372284-1ebf5880-00b1-11eb-8c8a-2ba380df5038.png)

**Comment by jurialmunkey** [comment]
I don't understand what the issue is. There's already a shadow on the large image. If you want a divider, turn the divider on in the skin settings.

If you mean that you want it to look like the poster is fading out into the background (i.e. like it is going into the background itself), then that's not possible - skinning engine doesn't provide the ability to apply a diffuse mask to a section of the screen.

**Comment by daking1512** [comment]
Ah gotcha, and yes I was thinking if its possible to have the movie/tv show posters fade into the background behind the actors photo but I guess the skinning engine prohibits that

Thanks for the response :D
