### ISSUE TITLE
[Feature] Hub widget transition animations

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.horizon#30]
When you focus a submenu item in the submenu hub, there is hesitation before switching to the corresponding hub widget, and no transition between the two. It just "hangs" and then switches to the new one.

**Comment by jurialmunkey** [comment]
The way it currently works is each hub submenu button sets a property to make the widget visible. There seems to be a bit of a delay in Kodi registering that the property has changed. I'm trying to find a better solution (I can't use a list because I need to be able to use auto width which is only available to button controls).

**Comment by drinfernoo** [comment]
Fair enough. I likely won't use hubs *a lot*, but was playing around and noticed it 😉

**Comment by jurialmunkey** [comment]
I've definitely noticed the delay myself and it is something I think needs to be fixed - I'm just not so sure *how* to fix it yet...

**Comment by jurialmunkey** [comment]
The delay should be fixed now. I'll look at adding transitions later.
