### ISSUE TITLE
[Bug](Since recent update) Widgets with ShowMore don't start at first item after reload.

### ISSUE THREAD

**Issue by DaisyF8** [jurialmunkey/skin.arctic.horizon#304]
There used to be a loading animation in the widgets upon reload.  Now you see the "Show More" entry right away. 

When the rest is loaded, the widget row is skewed all the way to the right and "Show more" has focus.

**Comment by meesterexx** [comment]
Can confirm, this happens on my build (Kodi 18.9, Win10x64) as well. Here are screenshots of the TMDB Helper movie widget loading, loaded, and initial focus (down arrow)
![loading](https://user-images.githubusercontent.com/13154733/97205300-a7ebad00-178d-11eb-93eb-357d7533ba8b.png)
![loaded](https://user-images.githubusercontent.com/13154733/97205329-b1751500-178d-11eb-9549-e71606397b60.png)
![focused](https://user-images.githubusercontent.com/13154733/97205345-bafe7d00-178d-11eb-9805-1a1d3b55fd42.png)

**Comment by jurialmunkey** [comment]
Should be fixed now.

It was due to a recent update which made the default widget limit be true unlimited (i.e. limit = None). Show more item has a condition to only show when widget contains a number of items equal to or greater than the limit for the widget. The problem was that Kodi was treating the `None` limit value as a `0` when comparing the two values. Added an extra check to only display the show more item if a widget limit is set
