### ISSUE TITLE
[Request] Movie Language in Info view

### ISSUE THREAD

**Issue by onlytanmoy** [jurialmunkey/skin.arctic.horizon#310]
Will it be possible to include language field in the Information view of a movie? below screen.
![Kodi_20201121_145156](https://user-images.githubusercontent.com/48493659/99880173-b18bf780-2c09-11eb-854b-564a7a178094.png)
It's only after scraping and playing this movie I realized its in Spanish language 😃

**Comment by jurialmunkey** [comment]
There's no "original language" field in Kodi. Closest thing is country which is already shown.

For local files I can display the Audio Track languages - which I already do as shown below:

![Honeyview_screenshot290](https://user-images.githubusercontent.com/4618719/99890138-5103c580-2cb0-11eb-866e-43394f0a3cd3.jpg)

**Comment by onlytanmoy** [comment]
@jurialmunkey OK I get it. Since I do not use local files in Kodi, never noticed that Audio track language field :)
Will it be possible to display the same field for online content as well?

**Comment by jurialmunkey** [comment]
Only if the plugin in question fills it. It is based upon the file being played and is not necessarily just one value - eg a bluray could have multiple audio channels for different language dubs so those all display if Kodi can read them from the file.

Since you mentioned scraping sources then not possible because there isn't a single source file to take these from and so language can only be known after playing

**Comment by onlytanmoy** [comment]
@jurialmunkey OK, thanks for the nice explanation :) cheers mate.

**Comment by onlytanmoy** [comment]
@jurialmunkey hiya, just thinking out loud, will it be possible to grab the Language info from trakt.tv? In the below link for example you will see a Language field.
https://trakt.tv/movies/unknown-origins-2020

**Comment by jurialmunkey** [comment]
The issue isn't getting that data, the problem is that Kodi doesn't have a standardised label for original recording language, it only has labels for country and audio track language. 

I can't add the info into the audio track details because it isn't audio info (eg it would make things like Spirited Away look like there was only a Japanese track when in reality many would watch the English dub and it would actually probably be the first hit in most cases).

It could go in a custom property but then it wouldn't get used in skins because only tmdbhelper will have that property and other plugins and the library won't. It'd just be some obscure property that I'm using CPU cycles to retrieve and add but no one actually has it in any skins.

**Comment by onlytanmoy** [comment]
@jurialmunkey Thanks a lot for the clear detailed explanation bud. Really appreciate it!
