### ISSUE TITLE
Toggle watched status toggles every episode of season

### ISSUE THREAD

**Issue by jonesthefox** [jurialmunkey/skin.arctic.horizon#317]
Hello there! I have some problems with the togglewatched function from kodi. It works as  intended with confluence, i guess it's skin related. Sorry, but i did not test this with movies.. 

What are the steps to reproduce this issue?
-------------------------------------------
1. map togglewatched to a button on your remote
2. navigate to tvshows, pick a show, pick a season, select a episode you want to toggle as (un)watched
3. hit that toggle button

What happens?
-------------
Toggles every episode of that season as (un)watched.

What were you expecting to happen?
------------------------------------
It should only toggle the selected episode. 
It should toggle the whole season when the season is selected, and the whole show when a show is selected.

**Comment by jurialmunkey** [comment]
Are you using the combined seasons/episode view? Because Kodi sees that as being the seasons level, so any action like that which you apply will be treated as if you were applying it to the whole season which you have focused (the episodes are just an extra widget container and Kodi doesn't see that as the current "path").

If you want to toggle individual episodes, you need to click select on the season button itself to go inside it (rather than just pressing down). Then you will be at the episodes level and should be able to toggle individual episodes.

**Comment by jonesthefox** [comment]
Yes, that was exactly what i did ;-)

Thanks for your help and this nice skin!
