### ISSUE TITLE
[Feature] Mouse/Touch Compatibility

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.horizon#32]
I haven't messed much with a mouse specifically, which may work well in all fairness, but the skin is basically unusable on a touch screen 😩

**Comment by jurialmunkey** [comment]
Kodi really needs dedicated skins for touch. 

Most things do work for me though with touch. Two finger tap in header works to open side menu. I can scroll and select widgets (albeit it is best to limit to two widgets per main menu item). Library nav is fine.

Main difficulty is not being able to "hover" like a mouse can to change main menu view - but that's a specific reason why Kodi needs dedicated touch skins because some aspects just need to be changed.

Touch navigation would be improved considerably if Kodi treated a single touch as a hover and a double tap as a click.

**Comment by drinfernoo** [comment]
One of the main things that wasn't working for me were the buttons in normal windows. I wasn't able to interact with buttons to install add-ons, pull up information, etc...

**Comment by jurialmunkey** [comment]
Ah I see. They work in the library view but in the info dialog for some reason...

**Comment by jurialmunkey** [comment]
Info dialog buttons were fixed. Other mouse/touch issues are probably not fixable without creating a separate skin.
