### ISSUE TITLE
[Bug] Widget information displays info from widget above

### ISSUE THREAD

**Issue by DaisyF8** [jurialmunkey/skin.arctic.horizon#325]
I just discovered the "Display Info" setting for widgets. Very noice.

A very minor nitpick in a very specific situation:

on my screen in order
Widget A Trakt Next Episode with "Display Info" unchecked
Widget B Watchlist with "Display info" checked

See picture... Widget B "Display Info" field will display info for active item in widget A (be it without extra art from OMDb if there is any).

![screenshot004](https://user-images.githubusercontent.com/10348988/104177675-7045e600-5409-11eb-8525-12dfcf1f6738.png)

**Comment by jurialmunkey** [comment]
Nothing can be done about this as kodi doesn't provide any controls to skins for positioning widget items in a group list on screen  - it just has some basic logic about position that in some instances I can use some sizing hacks to get it to behave how I want but in this instance it is difficult. 

Since depending on which way you scroll the info might appear on screen due to the next widget being position by kodi at the top rather than bottom, then I decided it was better to have the info panel adapt to whatever widget us focused on screen. Originally it was tethered to that one particular widget but I found it really confusing to have info for some other item that wasn't even on screen.

The best thing to do is to put widgets with info at the top of the group and widgets without info below - basically widget with info is two rows high so it always takes full position on screen, whereas a normal widget is only one row so it is positioned at bottom or top by kodi depending on which way you scroll (basically kodi just tries to get the widget on screen when you scroll to it but it only cares that it is on screen and doesn't give any control to the skin over where it is positioned)

**Comment by DaisyF8** [comment]
In that case (Info adapts to focused widget - which is totally fine and logical) it appears the art doesn't get fetched if it relates to the widget above. 

In the screenshots both widgets top and bottom are TmdbHelper Next Up.

Bottom widget gets art, while top widget doesnt for the same show.

**Comment by jurialmunkey** [comment]
The main problem is that with the widget templates, each widget is only really able to check whether itself is focused or not. It can't check which particular _other_ widget has focus, or where it is relative to itself or the screen.

So the choice here is either show art _only_ when self is focused, or always show art. Retrieving the correct art is relatively trivial, it is the visibility condition that is the problem. I go with showing the art only when focused because I don't want art to appear in the partially offscreen top row (e.g. imagine in your first pic you scroll one more down, the clearart will be aligned with the clock but it will be the art for the bottom row because that is what is focused - it gets really annoying and off putting with it changing whilst scrolling).

**Comment by DaisyF8** [comment]
Yes, it would become distracting. 

Also thanks for explaining with so much detail. I'd rather understand something instead of just accepting it, and you always make sure the first is possible.

[Solved]
