### ISSUE TITLE
Question: Adding new views for Advanced Emulator Launcher

### ISSUE THREAD

**Issue by mechevarria** [jurialmunkey/skin.arctic.horizon#326]
HI,
 I would like to add/customize a couple views for Advanced Emulator Launcher in Arctic Horizon like I did for Arctic Zephyr 2. I am having trouble understanding how the viewtypes are setup. How do you properly add new views for a specific plugin?

What I have tried:
I saw the logic in `skinviewtypes.jon` but I could not figure out how to create a rule just for `plugin.program.advanced.emulator.launcher`. It comes through as `"none"` in the interface. I tried adding extra views to the `"none"` element like this:
`"viewtypes": ["50", "51", "501", "55", "500", "52", "502", "53", "54", "504", "56", "57", "58", "59"]`
Which added views. but now there is only one view set for everything. In other words, I can't have poster row for the system select and square wall for the system game list. Its either poster row or square wall for everything. 

My ultimate goal is to help out and add/edit `Landscape Wall` for the system select (MAME, NES, etc) and `Info Wall` with either Poster or Square aspect for the individual games. 

I just can't figure out how to get started by combing the xml. Thanks

**Comment by jurialmunkey** [comment]
> In other words, I can't have poster row for the system select and square wall for the system game list. Its either poster row or square wall for everything.

You can't really do this as viewtypes are locked to content types in this skin. The addon needs to set different content types for different content.

The only real option you can do is setup rules for each individual path.

I don't use AEL myself so not sure of exact paths but you could do something like so:

```
"AEL-basedir": {
            "rule": "Container.Content() + String.IsEqual(Container.FolderPath,plugin://plugin.program.advanced.emulator.launcher/)",
            "viewtypes": ["50", "500"],
            "library": "50",
            "plugins": "500"
        },
"AEL-otherdir": {
            "rule": "Container.Content() + String.StartsWith(Container.FolderPath,plugin://plugin.program.advanced.emulator.launcher/) + !String.IsEqual(Container.FolderPath,plugin://plugin.program.advanced.emulator.launcher/)",
            "viewtypes": ["50", "500"],
            "library": "50",
            "plugins": "500"
        },
"none": {
            "rule": "Container.Content() + !String.StartsWith(Container.FolderPath,plugin://plugin.program.advanced.emulator.launcher/) +  !Window.IsVisible(MyPVRTimers.xml) + !Window.IsVisible(MyPVRSearch.xml) + !Window.IsVisible(MyPVRRecordings.xml)",
            "viewtypes": ["50", "500"],
            "library": "50",
            "plugins": "500"
        }
```

So basically these three rules all are possible when container content is None. 

The first rule "AEL-basedir" only works if the folder path is equal to the base folder path. The second rule "AEL-otherdir" works if the folder path _starts with_ the AEL path but _not_ if it is the basedir (so it doesn't overlap with our first rule). The none rule has the _not_ starts with bit added so that it doesn't overlap with either of the above two rules.

The names of the rules (e.g. AEL-basedir) don't matter that much, all that is important is that rules in each one are setup so that only one rule definition will ever be true at a time (that's why we need to add the "!" not condition to the none rule so that it doesn't overlap with the other rules we just made for the nonetype container content).

**Comment by mechevarria** [comment]
Awesome that does work. The views can now be set in the settings. What is not working is the `Choose viewtype` dialog does not populate with the viewtypes from those rules. I falls back to `none` and only shows `Tags, Squarelist`. Is there another place I need to add that rule?

**Comment by mechevarria** [comment]
I do have one last question. How do you change the default select action to go to item details (like how TV Shows and Movies do it) instead of just executing/launching on select.
I am looking to take advantage of the `trailer` button to play the game trailer. Might be a better solution than the 5 second timeout and autoplay from Arctic Zephyr 2.

**Comment by jurialmunkey** [comment]
Default select action is a kodi core thing, not a skin thing.

Kodi only allows changing onclick for widget containers. Not possible to override the onclick action for the main view container in media windows (well you can hack it with a fake button that takes focus but it isn't worth it because it will break a lot of other controls and will have all sorts of undesired behaviour you can't fix)

**Comment by mechevarria** [comment]
Yeah I have no intention to mess with kodi core behavior. Appreciate all the responses!
