### ISSUE TITLE
[Request] OMDB Ratings in a Lovefilm aspect widget

### ISSUE THREAD

**Issue by Logs22** [jurialmunkey/skin.arctic.horizon#339]
I'm not sure if this would be possible, but I tend to use the Lovefilm aspect as a Spotlight widget. Instead of having to show information on widgets with this aspect, I think it would be amazing if they Showed within the widget, or just the ratings outside of it. However I don't know if this is possible, which is why im leaving it here.

**Comment by jurialmunkey** [comment]
Yeah sorry unfortunately not possible. The skinning engine doesn't allow using window properties inside a list container - basically in any list it is only possible to use the properties attached to the item itself by the plugin that makes the list, not properties from an external source (which the additional ratings are because they are populated by the TMDbH service monitor).

**Comment by Logs22** [comment]
Ah thought that might be the case, thanks for the response!
