### ISSUE TITLE
[Feature Request]Auto hide Video & Music OSD

### ISSUE THREAD

**Issue by taoxtrece** [jurialmunkey/skin.arctic.horizon#34]
Hi jurialmunkey, first thanks for you words about Covid19 and give us the opportunity the have this early version.
Can you add the video and music osd auto hide option with counter like AZ2 in the skin settings plz.
And support for UpNext.
Thanks for all .

**Comment by drinfernoo** [comment]
As well as this, can we have the OSD dismissable by a subsequent touch/click?

**Comment by jurialmunkey** [comment]
> Can you add the video and music osd auto hide option with counter like AZ2 in the skin settings plz.

This feature was provided by SkinHelper, which I'm avoiding adding because it isn't really being maintained any more.

It's not possible to autoclose the osd in skin without the help of a script.

**Comment by taoxtrece** [comment]
Ok thanks for the info, and if you need help with UpNext, i can send you the correct files im using in AZ2

**Comment by jurialmunkey** [comment]
> 
> 
> Ok thanks for the info, and if you need help with UpNext, i can send you the correct files im using in AZ2

Yeah that might be useful thanks!

**Comment by taoxtrece** [comment]
[1080i.zip](https://github.com/jurialmunkey/skin.arctic.horizon/files/4357081/1080i.zip)

**Comment by jurialmunkey** [comment]
Thanks!

**Comment by taoxtrece** [comment]
Np, this weekend i think can send you the Spanish Translation for the strings.po ;)

**Comment by jurialmunkey** [comment]
> 
> 
> Np, this weekend i think can send you the Spanish Translation for the strings.po ;)

It's probabaly not worth it yet as there are many strings that aren't translated and also many strings that are unused left overs from AZ2
I'll be doing a clean-up of the strings soon. I'll let you know once it has been done and then a translation would be great!

**Comment by taoxtrece** [comment]
ok when you can, for az2 i need retouch a few details and can send you this weekend :)

**Comment by drinfernoo** [comment]
@jurialmunkey Is closing the OSD with another tap doable?

Also, do you know *how* Skin Helper accomplished the autoclose? We could just make a small helper script for it.

**Comment by jurialmunkey** [comment]
> 
> 
> @jurialmunkey Is closing the OSD with another tap doable?
> 
> Also, do you know _how_ Skin Helper accomplished the autoclose? We could just make a small helper script for it.

Yeah, definitely possible to close osd with a tap - should be pretty easy to add, just need a hidden button in the background which closes osd when clicked.

I'm not sure how it achieved autoclose, I would need to look at the code. I'm guessing some sort of service monitor that is triggered when osd is visible and waits until `system.idletime()` hits the required value. It might be possible to achieve in skin with a silent alarmclock with a timer that is reset when moving between items - but it would need to be a fixed value because it isn't possible to pass variable values to attributes inside the skin.

**Comment by drinfernoo** [comment]
@jurialmunkey What do you mean by a "fixed value"? Not able to change the timing of the OSD hiding, you mean?

**Comment by jurialmunkey** [comment]
> 
> 
> @jurialmunkey What do you mean by a "fixed value"? Not able to change the timing of the OSD hiding, you mean?

Yeah.

The skin engine doesn't let you do things like:
`System.IdleTime($INFO[Skin.String(OSD_Timeout)])`
`AlarmClock(Timeout,Action(Close),$INFO[Skin.String(OSD_Timeout)],silent)`

You have to put the actual value like:
`System.IdleTime(3)`
`AlarmClock(Timeout,Action(Close),00:03,silent)`

You can do things like
```xml
<onclick condition="Integer.IsEqual(Skin.String(OSD_Timeout),1)">AlarmClock(Timeout,Action(Close),00:01,silent)</onclick>
<onclick condition="Integer.IsEqual(Skin.String(OSD_Timeout),2)">AlarmClock(Timeout,Action(Close),00:02,silent)</onclick>
[etc.]
```

But that essentially means you need a condition for every single possible value - that's why a lot of options like widget limits only have a specific set of options rather than a user input.

**Comment by taoxtrece** [comment]
@jurialmunkey AZ2 Spanish Translation
[resource.language.es_es.zip](https://github.com/jurialmunkey/skin.arctic.horizon/files/4362033/resource.language.es_es.zip)

**Comment by jurialmunkey** [comment]
@taoxtrece @drinfernoo 
As of v0.1.29 you should now be able to set an autoclose OSD value. It appears to work well without a script. Possible values are Never, 03, 05, 10, 15, 20, 30 and 60 seconds.

Also added tap to close OSD ability and tweaked the hitbox of the seekbar to not need to be so precise.

---
Relevant Commits: https://github.com/jurialmunkey/skin.arctic.horizon/commit/2afd2046158a07508fb6ce4559f25b78296acb88 https://github.com/jurialmunkey/skin.arctic.horizon/commit/1f6802d6eab4f9ca3a2df36392709b4966c013ed

**Comment by taoxtrece** [comment]
Great news! Downloading...
