### ISSUE TITLE
[BUG] Matrix Issues

### ISSUE THREAD

**Issue by Fatal-Errol** [jurialmunkey/skin.arctic.horizon#352]
I understand that this skin does not support Matrix yet but based on this latest comment

https://github.com/jurialmunkey/skin.arctic.horizon/issues/349#issuecomment-782527392

the author is currently working on it. With this I think listing the issues that I see on matrix might help with the port.

I used this comment to install this skin on Matrix:

https://github.com/jurialmunkey/skin.arctic.horizon/issues/192

I also have to remove the gui version dependency in addons.xml

All in all no major issues, just the following small things:
- [x] OSD Controls: there is no "playlist" button even if the video has a playlist [WIN10/Android9]
- [ ] Startup Video: Right after the startup video plays, the screen goes black until I press the back button [WIN10/Android9]
- [ ] Addons Info View: Can't select anything so I can't open the addon. Pressing the directional buttons doesn't do anything.  Pressing OK button will display the addon "settings" [WIN10/Android9]

Wonderful skin and addon widgets loads considerably faster compared to 18.9 especially on my android TV. Thanks for this!

**Comment by Fatal-Errol** [comment]
Update.

>  OSD Controls: there is no "playlist" button even if the video has a playlist [WIN10/Android9]

Checking the code, it doesn't have a playlist button intentionally so not a bug.

>  Startup Video: Right after the startup video plays, the screen goes black until I press the back button [WIN10/Android9]

It is inconsistent in WIN10, sometimes it's ok sometimes not. Android9 is consistent though. Here is my log
[kodi.log](https://github.com/jurialmunkey/skin.arctic.horizon/files/6023309/kodi.log)

**Comment by RealJohnGalt** [comment]
One more issue, but not sure if matrix specific (don't have an earlier version to test): On Linux at least, external players as default don't work properly on linux through the play button on info dialog. They do work correctly played through the context menu.

an example of through the context menu (which works): INFO <general>: ExecuteAppLinux: "/usr/bin/mpvplay" "/mnt/ext3/Movies/SomeMovie.mkv"

Through the info dialog (which fails): INFO <general>: ExecuteAppLinux: "/usr/bin/mpvplay" "'"/mnt/ext3/Movies/SomeMovie.mkv"'"
2021-02-22 18:03:46.292 T:5703     INFO <general>: ExecuteAppLinux: Failure: 512

It's clear the argument is being changed through the info dialog.

**Comment by jurialmunkey** [comment]
@Fatal-Errol - There is now a Matrix version available from the Matrix branch:
https://github.com/jurialmunkey/skin.arctic.horizon/tree/matrix

I can reproduce the AddonInfo bug but I'm not quite sure what is causing it yet. I have a feeling that there is an undocumented to change to that dialog where it forces focus to a particular button ID but not sure yet - I'm looking into it.

Yep no playlist button on OSD controls - they are really due for an overhaul sometime soon because I feel like there are a lot of controls that don't really get used that much like FF/RW and clutter up navigation whilst other more useful controls like audio settings and playlist are hidden away in menus or not even available. 

I haven't had a chance to test startup video but I'll look into it soon.

@RealJohnGalt - I think that is a separate issue and probably would have been in Leia too. It is because the play button in the info dialog goes through TMDbH and is escaped.

**Comment by pkscout** [comment]
Just FYI regarding the AddonInfo issue. If you enable mouse support (assuming you have a mouse like device available), you can at least get to the buttons by mousing over them. And once you mouse over one, you can then use the keyboard/remote to move between them (at least until you close the AddonInfo Dialog).

**Comment by pkscout** [comment]
I'm not sure how I feel about one issue for all the Matrix issues, but I'm going to go ahead and put this here until I hear otherwise.  If I run the Netflix or Disney+ addons, Matrix crashes when I stop the video. This happens with AH, but not the default Estuary skin. There was something on the Team Slack about BusyDialog being opened twice (without being closed between) with Matrix, but my first look at the log (https://paste.kodi.tv/qujabuzono.kodi) shows a close for each open (until the last one that **might** be causing the crash).  The linked log is with Netflix.

**Comment by Drubei** [comment]
Regarding the Addoninfo page, the bug doesn't happen with all the addons.  Some of them you can select the buttons..  For example Toolbox Script, Keymap Editor, Skin Variables, and Library Node Editor works just fine.

**Comment by jurialmunkey** [comment]
@pkscout - Yeah I think better to have separate threads for separate issues. Do you want to open that one up separately (could add a tag like `[Matrix]` to the title to make it clear it is for Matrix only).

EDIT: Actually looks like someone has already added an issue here: https://github.com/jurialmunkey/skin.arctic.horizon/issues/356

**Comment by jurialmunkey** [comment]
@Fatal-Errol (and everyone else in this thread) - it was as I suspected, an undocumented force focus to a control in the dialog. Latest version on Matrix branch should fix it.

In the interest of keeping issues separate - could you open the startup bug as a separate issue and just add `[Matrix]` to the title so that it is tagged as a Matrix issue.

**Comment by Fatal-Errol** [comment]
Will do @jurialmunkey, thanks!

**Comment by RealJohnGalt** [comment]
> @RealJohnGalt - I think that is a separate issue and probably would have been in Leia too. It is because the play button in the info dialog goes through TMDbH and is escaped.

This seems to be correct. Should I file an issue on tmdbh instead?

Edit: selecting route PlayMedia to xbmc in TMDbH settings works correctly.
