### ISSUE TITLE
[Bug] Artwork Dump

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#355]
Artwork Beef is no longer compatible with Kodi 19. It has now been replaced with Artwork Dump

https://forum.kodi.tv/showthread.php?tid=360078

Artwork Dump installed

<img width="1517" alt="Screenshot 2021-02-24 at 20 36 07" src="https://user-images.githubusercontent.com/2873112/109064642-8f12ea00-76e2-11eb-9126-6707ccbe9f83.png">

Thanks

**Comment by jurialmunkey** [comment]
As far as I understand Artwork Dump isn't for selecting artwork, it just downloads the existing artwork that has already been added by the scrapers. There shouldn't be any need for skin integration.

In Matrix, the adding of clearlogos and other additional artwork types is now the responsibility of the scrapers. Artwork Beef has been discontinued and there is no replacement because it is no longer relevant.

**Comment by jurialmunkey** [comment]
FYI - Getting additional artwork types is generally as simple as enabling fanart tv artwork in the scraper you use and then refreshing the info of the movie/show.
