### ISSUE TITLE
[Bug] File names with commas are truncated and fail to play

### ISSUE THREAD

**Issue by jgilf** [jurialmunkey/skin.arctic.horizon#364]
Hi, 

Many thanks for this beautiful skin.

I'm experiencing an issue with playback on Matrix which I believe has been encountered previously (see #159). Any video I try to play that has a comma in the file name fails to play due to the path being truncated somewhere along the line. See below example from my logs.

> 2021-03-01 13:17:50.513 T:9850     INFO <general>: VideoPlayer::OpenFile: /mnt/youtube/World War Two [UCP1AejCL4DA7jYkZAELRhHQ]/WW2 Week by Week [PLsIk0qF0R1j4Y2QxGw33vYu3t70CAPV7X]/20200621 - The Polish-German War - WW2 - 001 - September 1
> 2021-03-01 13:17:50.514 T:10387    INFO <general>: Creating InputStream
> 2021-03-01 13:17:50.515 T:10387   ERROR <general>: CVideoPlayer::OpenInputStream - error opening [/mnt/youtube/World War Two [UCP1AejCL4DA7jYkZAELRhHQ]/WW2 Week by Week [PLsIk0qF0R1j4Y2QxGw33vYu3t70CAPV7X]/20200621 - The Polish-German War - WW2 - 001 - September 1]

The real filename in this example is: 

> 20200621 - The Polish-German War - WW2 - 001 - September 1, 1939 [IMPROVED] [1920x1080] [2b7GY4BSUmU].mkv

I understand that the easy fix is to simply remove the commas from the filenames but I was hoping there may be a solution on your end. I've tested playback on Estuary and it works as expected.

Thanks!

**Comment by jurialmunkey** [comment]
Am I correct in assuming that this only occurs when trying to play from the info dialog?

**Comment by jurialmunkey** [comment]
Also, full debug log please.

**Comment by jgilf** [comment]
Hey, sorry for the late reply. I've actually been trying to reproduce this bug to get you a full error log but haven't been able to for some reason. I can confirm that I was getting this behaviour within the Landscape Row view and not via the info dialog. I will try again to reproduce it later and will post a full debug log if I can.

**Comment by jurialmunkey** [comment]
Kodi controls the action when clicking directly on a library view item. It isn't possible for a skin to override this action, so that would be a Kodi issue.

The places where the skin can control the onclick action is in widgets and on buttons (e.g. play button in info dialog). Also, in the "Integrated" views (e.g. seasons view with episodes underneath), the section underneath that displays the episodes has a custom onclick because it is essentially the same as a widget but that's the only place in the library.
