### ISSUE TITLE
Req: Clicking on an actor on info page to do library search

### ISSUE THREAD

**Issue by jhs39** [jurialmunkey/skin.arctic.horizon#399]
When looking at the info page for a movie currently clicking on an actor does an internet search and pulls up movies that aren't actually in my library.  I would like to be able to click on the actor's name/picture and have it show everything with that person that's in my library and available to watch.

**Comment by jurialmunkey** [comment]
Turn off "use online info" in the info dialog list options found in skin settings.

**Comment by jhs39** [comment]
Thanks.  That worked but is there a way to change the view of the search results?  When I click on an actor now I do get a list of movies in my collection but the view is a vertical list of titles with a tiny horizontal thumbnail to the left of each title.   I would like to change it to something more attractive or with more information.

**Comment by jurialmunkey** [comment]
No, not possible I'm afraid. Kodi uses the the select dialog to display that list and that's what the select dialog looks like in this skin - if I changed how that dialog looks, it would be changed everywhere it is used in the skin not just for actors

**Comment by jhs39** [comment]
I'm not sure if that means it's impossible for the user to change the look of the select dialogue because that's not a feature built into your skin or if the feature itself is impossible.  In any case, thanks for the reply.

**Comment by jurialmunkey** [comment]
> I'm not sure if that means it's impossible for the user to change the look of the select dialogue because that's not a feature built into your skin or if the feature itself is impossible. In any case, thanks for the reply.

Not a feature in the skin.

You can change the look of the dialog by editing the skin. The problem is that Kodi uses the select dialog for pretty much every situation where you need to select something from a list of items, not _just_ for selecting a movie that a cast member was in. So if you change the appearance of the dialog, it will change _every_ select dialog not just the cast movie one. 

A different appearance like you are proposing is not going to make much sense for a lot of things the select dialog is used for such as selecting an interface language, choosing a skin, installing addon dependencies etc.

**Comment by jhs39** [comment]
Understood.  Thanks.
