### ISSUE TITLE
[Feature Request] Auto-Fit Season Titles

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.horizon#40]
Can the season buttons be made to auto-fit width for seasons with titles, like these?

![image](https://user-images.githubusercontent.com/2319508/77191234-dedf3f00-6a97-11ea-9fb5-c57d55950455.png)
![image](https://user-images.githubusercontent.com/2319508/77191570-60cf6800-6a98-11ea-8411-9b15fe6bea56.png)

**Comment by jurialmunkey** [comment]
Unfortunately not. Because the season is the container's folderpath, it has to be in a list and lists don't have autosized items. Only actual buttons can be autosized, but buttons can't have a folderpath. There are some ways to do it with a hidden list but that causes other issues.

In latest version I've widened the buttons slighty to better accommodate these non standard season names. Really long ones will still be cut-off but the majority should be fine

![Honeyview_screenshot650](https://user-images.githubusercontent.com/4618719/77209837-7bb2e280-6b53-11ea-91aa-9fa1e4c9ac76.jpg)
