### ISSUE TITLE
Webdav files get 401 error

### ISSUE THREAD

**Issue by justinkruit** [jurialmunkey/skin.arctic.horizon#406]
Whenever I try to play a file from my library that's from a webdav location, the log shows 401 errors. I don't have this problem with the normal skin, only when using Arctic Horizon. It also works fine if I go to the media sources, open the webdav location, and play them from there when using Arctic Horizon.

Log when using Arctic: https://pastebin.com/8wsgrw5j
Log using default skin: https://pastebin.com/5K9tgzNu
(I've replaced my cloud storage url with mypersonalcloud.com for security reasons)

From what I see, it looks like Arctic Horizon doesn't use the username and password when trying to open a webdav file resulting in 401 errors.

**Comment by jurialmunkey** [comment]
How exactly are you trying to play these files (e.g. by pressing play button in info dialog? Directly clicking on the file? etc.) Because skins generally don't have anything to do with how files are played. The only thing I can think is that you're trying to play via the play button in the info dialog because that is the one place where the play method is different from Estuary (In AH I need to use a special script to close out the TMDbHelper info windows before filenameandpath of the item is passed to Kodi PlayMedia function). 

If that's the case (that you are playing via info dialog), then you should change your default select action from "show information" to "play" so that you can play something by clicking on it (you can always long press and choose info instead).

**Comment by justinkruit** [comment]
I try to play the episode directly from the library, just pressing on the episode. Just tried to get the info dialog, and even that isn't working apparently? None of the webdav episodes let me open the Context menu, while it's working fine with other files and the default theme.

**Comment by jurialmunkey** [comment]
In that case, not a skin issue because the action when clicking on an item to start playback is handled by Kodi and not the skin, so it is the exact same action as in the default skin.

I'm fairly certain it is because whatever shortcut you are using to enter the library in Arctic Horizon is not setting up your webdav password. You can see that by comparing the logs:

In your default skin log the filepath looks like this;
```
davs://USER:PASSWORD@mypersonalcloud.com:443/remote.php/webdav/Media/TV%20Shows/Avatar%20-%20The%20Last%20Airbender%20%5BBlu-ray%5D/Avatar.The.Last.Airbender.S02E17.Lake.Laogai.1080p.BluRay.x264-nikt0.mkv
```

Whereas when you are calling the filepath in Arctic Horizon the "USER:PASSWORD@" part is missing, hence why you get a 401 error (401 means "unauthorized").

You most likely need to change the shortcuts on your home screen to point to the correct path. I don't use webdav so I'm not really sure how you go about that but I'm fairly confident that is your issue.

You can configure home shortcuts in the home customisation dialog in skin settings.

**Comment by justinkruit** [comment]
Thanks to a tip in the issue #411, I learned that Landscape Integrated is like a special view, and that you need to press the season on top to open the Landscape view mode of it. 

Using this knowledge, I went back to my webdav files, and they started playing if I went into Landscape view mode. So it seems like webdav files break using the Landscape Integrated view, by not properly adding the login details
