### ISSUE TITLE
Playing and stopping a TV Show doesn't switch sound bar from DTS Back to PCM, also request for Folder/Category Names.

### ISSUE THREAD

**Issue by Kristijan1001** [jurialmunkey/skin.arctic.horizon#419]
Hello, Posted this over kodi forums might as well mention it here. 

I am experiencing a Bug with the skin. When having Audio Passthrough on for my soundbar. If you play a TV Show with DTS Sound. The Soundbar switches to it, once you click stop on the show. The soundbar doesn't go back to PCM so there is no sound afterwards on KODI. There is a workaround tho. If you play the tv show then click the back button on the remote, when in the previous menu, if you press Stop, to stop the show It will actually stop and switch back the soundbar to PCM and Kodi will have sound again.

This is only happening with TV Shows. Movies are perfectly fine. Tested it with DTS DTS HD etc. They all work fine when pressing stop while the video is playing. For some reason this weird bug only happens with the TV Shows while in the video. 

I Also want to ask a question or kind of a request if possible. The basic view of the theme is awesome and the best. There is one issue tho. If there are categories or sections that don't have movies/shows, those sections are showed as "Cover" type menus. Problem here is. Lets say for example in file manager and some addons i have. You can't see the folder names, only default covers that give out 0 info on what is selected. So you have to switch "View types" temporary just to see the folder names/category names so you can actually see what you are selecting, then switch back so you can still enjoy the default view for the movies.  My request if possible is to have a Text or something in the top left corner showing what is selected.  Thank you.

Examples, as you can see there is no way to tell the name of the categories/folders.

![kodi_oVvWOwEav1](https://user-images.githubusercontent.com/24441639/121734202-bf955d00-caf4-11eb-88fa-a3a5b4ffd7c4.png)
![kodi_s9euFa4S59](https://user-images.githubusercontent.com/24441639/121734210-c15f2080-caf4-11eb-88c1-e16c84212b03.png)

**Comment by DaisyF8** [comment]
I really don't think this is Skin related, but did you turn on CEC (remote controle via hdmi) on your TV ?  Audio switching and other stuff is negotiated on that layer. It can work without CEC depending on brand, but by design CEC should be enabled for audio return channel to work.

To be complete, this is not in Kodi but in the menu of your tv. Since only stereo or compressed audio can be sent over ARC your TV may actively be switching or re/transcoding depending on what Kodi is setup to output for audio. 

In Kodi, MAYBE also turn off "Dolby Digital Plus (E-AC3) capable receiver" and "DTS-HD capable receiver".

**Comment by jurialmunkey** [comment]
Not skin related. Skin doesn't control audio layer.
