### ISSUE TITLE
Genre Icons, Some Missing

### ISSUE THREAD

**Issue by ShaVerZ** [jurialmunkey/skin.arctic.horizon#426]
I was advised to visit and raise my issue, I hope I'm doing this correctly.

I have a number of genre icons missing and I've had this problem for a while now, is there any way of resoving my problem? I've had this issue for a good while now but can't seem to find a resolution anywhere 😞

![Arctic Horizon Genre Icons (1)](https://user-images.githubusercontent.com/58187200/126040722-515464af-bb63-4881-8195-0b9852f6b82a.jpg)
![Arctic Horizon Genre Icons (2)](https://user-images.githubusercontent.com/58187200/126040724-2d3d8d6b-86fe-4c56-b493-ebe242678d31.jpg)

**Comment by alKODIque** [comment]
Hi,
I don't think this is a skin problem because AH uses icons from existing pack. I think there is simply no icons for those genres in the pack that you are using

**Comment by Goldenfreddy0703** [comment]
Hi, sorry for not responding cause i never use artic horizon due to limitations with the game views still not working. Best thing i do recommend using is AutoWidget. AutoWidget is basically like superfavorites but way better where you can customize your shortcuts and icons and menus for other addons, I use it to add icons to seren and other addons and its beena huge help for me. 

https://forum.kodi.tv/showthread.php?tid=352934

**Comment by jurialmunkey** [comment]
As AlKODIque points out - the icons need to be added to the icon pack that you're using. All the skin does is get `iconpack/{genre-name}.png` so if there's no .png for that genre in the icon pack then there won't be an icon.
