### ISSUE TITLE
[Request] OSD Auto-Hide skin setting update

### ISSUE THREAD

**Issue by Nuklear92** [jurialmunkey/skin.arctic.horizon#438]
Is it possible to replace the current setting of Auto-Hide OSD in A.H which requires this ToolBox Add-On dependency to work with the one you implemented in Eminence recently that works without it? 🤔

![image](https://user-images.githubusercontent.com/76958541/137939543-caebd819-3c5c-4577-ac52-87b126d718f6.png)

**Comment by drinfernoo** [comment]
Eminence also has the ToolBox Script dependency... It is used to show the dialog of options, but the actual functionality is handled natively in both skins.

**Comment by jurialmunkey** [comment]
Yeah toolbox is just a small addon used to display setting select dialogs. It has nothing to do with how the auto close osd actually works - toolbox is just needed to display the dialog to select the duration of the settings. The method used in both skins is pretty much exactly the same (I copied the Arctic Horizon method to Eminence) 

Once you have the setting you like, you can uninstall toolbox if you really want (though it is super small addon and doesn't really do anything else other than make it easier for skins to open select dialogs - it only runs when specifically called by the skin to open a dialog).

I don't install it as a dependency because it is only needed for a handful of settings - so may as well only install it on demand when a user wants to change those specific settings

**Comment by Nuklear92** [comment]
Thanks for the explanation on how it works. I had no clue I could uninstall it after selecting the Auto Hide OSD timer I want. Well, since you say it's fairly small and doesn't really has any major hit on memory or power from Kodi I'll leave it there then. 👍

**Comment by jurialmunkey** [comment]
> I had no clue I could uninstall it after selecting the Auto Hide OSD timer I want.

Most skins that use toolbox just install it as a required dependency when you install the skin, so normally you wouldn't even notice that it got installed.

I try to keep required dependencies to a minimum because they can't be uninstalled without first uninstalling the skin and anything that isn't absolutely essential to the skin I like to keep optional.

**Comment by drinfernoo** [comment]
@jurialmunkey Well, you can still list them as *optional* dependencies 😉

**Comment by jurialmunkey** [comment]
> 
> 
> @jurialmunkey Well, you can still list them as _optional_ dependencies 😉

The optional tag doesn't work like that (unless there was a change that I'm not aware about). The optional tag allows for settings in addonsettings to install specific addons when enabled
Example: https://github.com/xbmc/xbmc/commit/7e91ec76c8082bc04d73a82f99285fedc865e944

e.g. having this in addon.xml
`<import addon="plugin.video.youtube" version="2.1.0" optional="true"/>`

will allow for this in settings.xml so that when the user clicks this setting in addonsettings dialog it will install youtube
`<setting label="30004" type="bool" id="trailer" default="true" enable="System.HasAddon(plugin.video.youtube)"/>`

Since skins don't use the addonsettings dialog, it doesn't do what you're thinking it does. That's the specific reason InstallAddon() command was added: https://github.com/xbmc/xbmc/pull/8419


Here's some specific history -- thread started by me from 6 years ago 😉 
https://forum.kodi.tv/showthread.php?tid=231104
