### ISSUE TITLE
Problem with Shutdown & Reboot

### ISSUE THREAD

**Issue by MarceloBorja** [jurialmunkey/skin.arctic.horizon#439]
So, I'm having this weird problem with this skin. Every time i try to shutdown the system or reboot the system. Nothing happens it just freezes the system. If i switch to another skin, everything gets back to normal. I'm using Coreelec Matrix 19.3 on a Odroid N2. Thanks

**Comment by drinfernoo** [comment]
Make sure to use the default actions (that are provided by the skin) for those options.

**Comment by roc16** [comment]
@MarceloBorja same is happening with me on the same version and hardware. I can’t remember when it started happening, either when I upgraded Coreelec or the skin but for sure just in the last two weeks. Did you get it fixed?

@drinfernoo can you explain what you mean by default actions? The only thing I changed was the order of the power menu but of course something could have happened.

Thanks.

**Comment by alKODIque** [comment]
@roc16 
When you first install the skin, there is no Shutdown menu on the default shortcuts of the skin. You have to add one.

In the default shortcuts provided by the skin, you have to select ''ActivateWindow(shutdownmenu)'' located in ''Common'' for this shortcut

(my shortcuts are in french, but you will find it at the same place):

![Screenshot_20211108-071136](https://user-images.githubusercontent.com/49578130/140740044-45e1d42d-dd98-467f-b16a-6c1a7e35aaa1.png)

![Screenshot_20211108-071242](https://user-images.githubusercontent.com/49578130/140740106-1baef1ff-29be-4a2a-9a97-4bda7eab8f98.png)

![Screenshot_20211108-071303](https://user-images.githubusercontent.com/49578130/140740159-b59e7e9c-d635-4450-94dd-032a8cd131db.png)

You will now have the default action on your home page. I never had problem with shutdown using it

![Screenshot_20211108-071435](https://user-images.githubusercontent.com/49578130/140740342-96e09088-a89d-432e-90f8-066478d5f509.png)

(Nvidia shield, kodi 19.3)

**Comment by roc16** [comment]
@alKODIque thanks for the detailed. I deleted the current power menu item and readded as per your instructions. Looks to be working now. Cheers!

**Comment by jurialmunkey** [comment]
This issue happens because you've inherited your skinshortcuts setup for the main menu from another skin and that other skin has misconfigured the shutdown action.

As AlKODIque points out, the default layout for Arctic Horizon's home menu doesn't even include a shortcut to the powermenu or any shutdown option, so if you've got a power shortcut there then you've either inherited it from another skin or added it yourself.

You can restore Arctic Horizon's default menu setup by going to:
`Skin Settings > Home > Customise home menu > Restore menu items > Reset to skin defaults`

Then you can add a shortcut to open the power menu as alKODIque demonstrates (or create a shortcut directly to shutdown). You can customise the power menu that opens in
`Skin Settings > Lists and other > Customise power menu`
