### ISSUE TITLE
[Question] spoilers stop working

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#440]
For some reason, spoilers stop working. I haven't changed my settings.

<img width="842" alt="1" src="https://user-images.githubusercontent.com/2873112/139561165-8850dcb4-2e6c-4bd1-b600-bd9dbb72c2ca.png">

<img width="1522" alt="2" src="https://user-images.githubusercontent.com/2873112/139561184-b21e6cfd-41e4-496f-9f5b-ade344d19c7d.png">

<img width="1522" alt="Screenshot 2021-10-31 at 00 32 07" src="https://user-images.githubusercontent.com/2873112/139561205-ac072990-fbd1-42b7-aa93-805688aaaf9d.png">

Thanks

**Comment by jurialmunkey** [comment]
What version of TMDbH are you using?

**Comment by Blurayx** [comment]
4.4.15
I found the issue. it's a bug with Kodi-19.3. when I downgrade back to kodi-19.2, it works.

**Comment by jurialmunkey** [comment]
>  I found the issue. it's a bug with Kodi-19.3. when I downgrade back to kodi-19.2, it works.

Ah, yep realised I was still on 19.2 on my laptop. Going to 19.3 I can recreate. It's actually because the spoiler thumbs were _fixed_ in 19.3 to work properly now -- but that meant my previous workaround in the skin then was broken.

Can you test the version I just pushed? 

It should fix it for 19.3 and the behaviour should now properly follow skin + plugin preferences - e.g.

- No Spoilers + Unwatched = Fanart or Landscape depending on Skin settings
- No Spoilers + Watched = Thumb, Fanart or Landscape depending on TMDbHelper settings

**Comment by Blurayx** [comment]
Fixed 😀
when you get spare time can you please fix the same issue for Eminence 2?

Thanks

**Comment by jurialmunkey** [comment]
>  when you get spare time can you please fix the same issue for Eminence 2?

Will do!
