### ISSUE TITLE
Coreelec Reboot to eMMC/NAND

### ISSUE THREAD

**Issue by labdiynez** [jurialmunkey/skin.arctic.horizon#442]
Added a Reboot to eMMC/NAND option in Power button.

**Comment by labdiynez** [comment]
@jurialmunkey closed reason?

**Comment by jurialmunkey** [comment]
> 
> 
> @jurialmunkey closed reason?

Because it isn't a bug. You can already customise the power menu and add whatever you want to it in
`Skin Settings > Lists and Other > Customise power menu`

**Comment by labdiynez** [comment]
@jurialmunkey  I don't see reboot to android option for coreelec.

**Comment by drinfernoo** [comment]
@showkubii Maybe you should have been more specific.

In any case, there's likely not any way to do that, since you often have to move a physical switch on the device to choose between the two boot options, depending on the device.

**Comment by labdiynez** [comment]
@drinfernoo
I tried adding it manually but it didn't work.
powermenu.DATA.xml

```
  <shortcut>
    <label2>Power Menu Shortcut</label2>
    <label>Reboot to Android</label>
    <action>System.ExecWait("/usr/sbin/rebootfromnand")</action>
    <action>Reset()</action>
    <visible>System.PathExist("/dev/env")</visible>
    <icon>special://skin/extras/icons/android.png</icon>
  </shortcut>
```

**Comment by jurialmunkey** [comment]
Ah I see what the problem is - it requires two actions to run this command but you can only set one from the dialog. You need to be more descriptive about the exact issue when creating a bug reports / feature requests.

Please try latest version I just pushed. You should now have a "Reboot to Android" available in "Kodi Commands"
`Customise Power Menu > Choose Item for Menu > Kodi Commands > Reboot to Android`

**Comment by labdiynez** [comment]
@jurialmunkey 
I have tested it works. Thank you for fix.

**Comment by mrXoo** [comment]
Please could you add this fix to the leia branch. Its working great in matrix
