### ISSUE TITLE
Arctic Horizon and Artwork Beef slowdown

### ISSUE THREAD

**Issue by sammy2142** [jurialmunkey/skin.arctic.horizon#48]
After installing artwork beef and after running a library scan to download new artwork, I've got a huge slowdown in poster loading in the movie and tv shows section.
Browsing through all movies I experience missing posters which can take 20 seconds to load in (before they were instant). 
This is not a one time load either as I keep getting more and more posters loading in (even ones which had previously loaded in). Even thumbnails in the settings menu become very slow to load in after browsing an affected library.
![slow_poster](https://user-images.githubusercontent.com/5837771/77260854-5b357600-6c82-11ea-8e73-a268cfa46f56.png)
Removing artwork beef didn't fix it - I had to remove the library and re-add it to get it back up to speed. 

For reference I'm running kodi on an ssd and ryzen 2600 and the posters normally are instant without artwork beef installed.

**Comment by drinfernoo** [comment]
I think this has actually been a symptom of Fanart.tv being overloaded for the last few days or a week?

**Comment by jurialmunkey** [comment]
Yeah this is nothing to do with the skin.

How images work in kodi:
- The scraper (e.g. Artwork Beef) writes the hyperlink to the http url in the relevant Kodi library database Art() entry. 
- The skin references the artwork via ListItem.Art()
- Kodi checks to see if the http url is listed in the `userdata/Database/Textures13.db` database cache. 
- For images that aren't cached, Kodi will download the image into local folders found in `userdata/Thumbnails/*/`.
- An entry is then written to `userdata/Database/Textures13.db` which links the online url to the local image (so it doesn't need to be downloaded again).

It takes time for the Kodi background loader to cache a large number of new images, which can be compounded by a slow (or non existent) response from the artwork provider (because it has to wait for each image).

**Comment by sammy2142** [comment]
Thanks for the replies - it seems to keep downloading images when cycling through all my movies even ones that should have been previously cached. Is this expected behaviour?

**Comment by jurialmunkey** [comment]
> 
> 
> Thanks for the replies - it seems to keep downloading images when cycling through all my movies even ones that should have been previously cached. Is this expected behaviour?

I'm not certain but I think there is a memory limitation on the background loader, so when it has a large number of images to cache it can impact its ability to display all the images. 

It's just something that happens - particularly with Artwork Beef as it sets a large number of image types e.g. compare normal Kodi library setting only Poster and Fanart versus AB setting Poster, Fanart, Extra Fanart, Landscape, ClearArt, Clearlogo, Banner, Thumb, Key Art etc.

Once everything gets properly cached then it will settle down and work correctly.

**Comment by jurialmunkey** [comment]
In the past I've used the Texture Cache Maintenance utility to force caching of the whole database. I'm not sure if it still works (been a while since I used it)
https://kodi.wiki/view/Texture_Cache_Maintenance_utility

**Comment by sammy2142** [comment]
Thanks for the explanation of how it works. I have reduced the amount of images to download in artwork beef and the interface is now responding smoothly again.
