### ISSUE TITLE
[Feature] "Show more..." item on widgets

### ISSUE THREAD

**Issue by jurialmunkey** [jurialmunkey/skin.arctic.horizon#50]
Have an option to display a "Show more..." item on widgets that will allow you to browse into the widget.

Not sure if it would be preferable to have individual settings for each widget or a global setting.

Maybe also only show if `NumItems = Limit` so that it isn't shown if all items are available in the widget?

**Comment by drinfernoo** [comment]
As a bonus to this, something I've been wondering about:

I have all my widgets set up with TMDbHelper right now, and showing the "Next Page" option, but most of them are sorted by `random`, so that item tends to get mixed in with the rest.

Would it be at all possible at the skin level to "force" that type of item to the **end** of the widget?

**Comment by jurialmunkey** [comment]
As far as I know, its not possible. Definitely not at the skin level. What's really needed is a way for the plugin to mark an item to not be sorted by Kodi.

**Comment by drinfernoo** [comment]
@jurialmunkey I expected that would be your answer, but thought I'd throw it out there 😉

**Comment by jurialmunkey** [comment]
Added v0.1.53
---
Relevant Commit: https://github.com/jurialmunkey/skin.arctic.horizon/commit/5b1042650fed965dd4f1d38efcfe4474bc722115
