### ISSUE TITLE
[Feature] Custom Viewtype for files

### ISSUE THREAD

**Issue by taoxtrece** [jurialmunkey/skin.arctic.horizon#53]
Hi @jurialmunkey can you add a custom viewtype for files? Some files only show the name pressing the info button.
![Screenshot_v0 1 36](https://user-images.githubusercontent.com/58227846/77331899-a783c300-6d21-11ea-8b09-1f1c6314ded6.png)

**Comment by drinfernoo** [comment]
If the add-on is declaring content correctly, this isn't needed.

**Comment by taoxtrece** [comment]
There isn't in addon, are folders with strm files from an archive path.

**Comment by drinfernoo** [comment]
This isn't where you should be browsing library content. Scan it into your library and access it via standard library views.

**Comment by taoxtrece** [comment]
That's not the problem, the issue is if you want navigate on the files from an Archive shortcut for example don't showed the names in display.

**Comment by taoxtrece** [comment]
yep

**Comment by jurialmunkey** [comment]
Ah, yeah maybe a fallback list view would be useful in these circumstances.

I've never understood why in files view Kodi sets the content type to what the source would be in the library rather than just setting it to files.

I'll have an update shortly.

**Comment by taoxtrece** [comment]
Thanks @jurialmunkey!

**Comment by jurialmunkey** [comment]
Okay should be fixed in v0.1.38
List view should be used by default for Files mode in library (regardless of content type). There is an option in the side menu (2x left) to switch the view back to the standard view for the content type
https://github.com/jurialmunkey/skin.arctic.horizon/releases/tag/v0.1.38

--- 
Relevant commit: https://github.com/jurialmunkey/skin.arctic.horizon/commit/68130fb7d1615c780eb9628492f2b3b710aee029

**Comment by drinfernoo** [comment]
Side menu??

**Comment by jurialmunkey** [comment]
> 
> 
> Side menu??

It's the options menu from the options button. In list view there is no options button, so you need to access it by pressing left from the scrollbar -- I realised when I added this files list view feature that the menu was missing from the list view (because no options button), so it has now been added to make it possible to access these options.

**Comment by taoxtrece** [comment]
Works great! very usefull for addon list too
![Screenshot_20200324-021801](https://user-images.githubusercontent.com/58227846/77379877-1856c980-6d7a-11ea-943e-697851c6877d.png)

**Comment by jurialmunkey** [comment]
Excellent. Thanks for testing 😄
