### ISSUE TITLE
[Meta] Shared Element Transitions?

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.horizon#55]
Not exactly a request, but more of an idea that may be reworked or used differently:

Does the Kodi skinning engine allow for the flexibility to do something along the lines of Android's [Shared Element Transitions](https://developer.android.com/training/transitions/start-activity)?

The idea being, you trigger opening a window by tapping on a certain piece of content, which animates itself into a more prominent "detail" position in the new window. I think this would add a very interesting flow to the Kodi experience, that I haven't seen any skins do.

For what it's worth, these animations are illusory. The windows don't *actually* share the elements, but the way they are positioned and animated in each window makes it appear that they do.

Is it possible?

**Comment by jurialmunkey** [comment]
It can be done but it is difficult because there are so many different scenarios to account for. I guess the main place you might do it is transitions from poster list to info dialog where the poster would zoom into position of the info dialog.

The tricky thing is that it's not possible to animate individual items in the list, so you have to fake it by creating duplicates that only exist for the purposes of the animation. It's a lot of work for minimal pay-off.

There was a transition animation from poster to info like that in Alaska:
https://youtu.be/kBBIuEQv2C8?t=10

**Comment by jurialmunkey** [comment]
That being said, I do hope that by simplifying so there is only one view, I might be able to have some more complex transition animations eventually.

**Comment by drinfernoo** [comment]
Fair enough. Mainly I just wanted to start a discussion about whether it was feasible or not 😅

Your answer was basically what I expected, so I'll close this one for now 👍
