### ISSUE TITLE
[Meta] Screensaver Widgets

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.horizon#66]
For what it's worth, I thought it may be a more "fluid" setup experience if the paths/labels for the screensaver could be set from Skin Settings. That should work just fine, and not need the stuff that I implemented in the screensaver's settings.

Using enough skin strings in that way would even let users choose which widget gets displayed underneath, and even multiple widgets. I'm not sure what you've got planned, but I just thought it may be more flexible and less hacky (😅) to do it that way, especially since you're basically just launching an unrelated window now anyways.

Let me know if I need to make any more changes to Arctic Mirage 👍

**Comment by jurialmunkey** [comment]
Yeah, I think that would make the most sense too. Remove the settings from the screensaver and have them implemented in the skin instead.

It currently only uses the Mirage setting if it is set, otherwise the fallback is to the fullscreen widget path. Would make sense for that to just be the one path to make things more consistent.

**Comment by drinfernoo** [comment]
With that in mind, I could likely completely remove the settings in the screensaver... Do you intend on making it a required dependency? I would almost just make the skin a dependency of the screensaver, since you're the only one that's done any skinning on it (besides my piss-poor attempt at a Netflix clone), and without settings it would be useless.

**Comment by jurialmunkey** [comment]
> 
> 
> With that in mind, I could likely completely remove the settings in the screensaver... Do you intend on making it a required dependency? I would almost just make the skin a dependency of the screensaver, since you're the only one that's done any skinning on it (besides my piss-poor attempt at a Netflix clone), and without settings it would be useless.

I guess the alternate method might be to leave the settings there just for the cases that you mention. Instead, I'll just use `Skin.String(screensaver.arctic.mirage.path)` as the default fullscreen widget path (instead of the separate setting of `Skin.String(widgetpath)` ). That way it works both ways.

I wouldn't want to put it as a dependency so that people aren't forced to use it, but I will add it to the "Manage Dependencies" section for easy install. I'll look into seeing if there is a way that the skin can set what screensaver is used - then I can just have a toggle button in the skin settings.
