### ISSUE TITLE
Disabled widgets remain on menu but are "invisible"

### ISSUE THREAD

**Issue by jweinreich** [jurialmunkey/skin.arctic.horizon#72]
Version 0.1.49

Disable widget B (don't delete just disable) any widget and go back to a main menu, movies for instance.
You can notice the widget is still there when scrolling through the remaining ones, so to move from widget A to widget C you actually have to go through widget B, which is invisible but still there.

**Comment by jurialmunkey** [comment]
Just delete the widget if you aren't using it. It's not possible to have disable working for widgets.

By default, Skinshortcuts only allows for attaching one widget to each menu item. Further widgets need to be added as custom properties which cannot be rearranged. To get around that limitation, I've used a few tricks to create widgets based instead upon a secondary submenu.

Since it is really just a submenu, I can't remove the disable option without also taking it away from *real* submenus.

**Comment by jweinreich** [comment]
Got it, thank you.
