### ISSUE TITLE
[Bug/Feature Request] Missing Clearart and Ratings on "Spotlight" Widget

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.horizon#75]
![image](https://user-images.githubusercontent.com/2319508/77676039-fceee880-6f4a-11ea-8357-40ccf1fab5e5.png)
I've got both my OMDb and Fanart.tv keys in TMDbHelper, but don't seem to be getting either ratings or clearart displaying on the home screen when using a single "spotlight"-style widget.

**Comment by jurialmunkey** [comment]
Yeah I've known about this issue for a while. The problem is that is difficult to set the TMDbHelper WidgetContainer onup/ondown of mainmenu because it is difficult to know what the next ID will be -- that meant you would end up with the wrong ratings being shown, so I had to disable it.

That being said, I think I've actually managed to figure out a way in the latest version to use some clever refocusing with a silent alarmclock to get the proper ID.

**Comment by drinfernoo** [comment]
Ratings are working for me now, but I'm still not seeing clearart 😫

**Comment by jurialmunkey** [comment]
There's no clearart because it would be cut-off when the menu is open.

**Comment by drinfernoo** [comment]
Oh... bummer ☹️ I was really looking forward to it 😅

**Comment by jurialmunkey** [comment]
> 
> 
> Oh... bummer ☹️ I was really looking forward to it 😅

I guess it could be faded in on focus of the widget (could also possible do a slide animation) - I just don't like the look of it being cut-off when the menu is open.

The other roadblock is that it needs a bit more space than there currently is, so the plot width would need to be reduced -- that would have an impact on widgets that don't have clearart (though not the end of the world as I've already reduced width since reading full screen width text is quite difficult on a larger tv).

**Comment by drinfernoo** [comment]
@jurialmunkey I was going to suggest a subtle fade, as I think that would actually look really nice 👌

**Comment by drinfernoo** [comment]
With a fade in on the homescreen spotlight, should a fade be put on the rest in other views?

**Comment by drinfernoo** [comment]
Working beautifully now :+1: Thank you!
